(()=>{
const nWater=1.333,nAir=1,rad=Math.PI/180;
const split=document.querySelector('[data-id="split"]'),angle=document.querySelector('[data-id="angle"]'),lens=document.querySelector('[data-id="lens"]');
if(!split||!angle||!lens)return;
const splitC=split.querySelector('canvas'),angleC=angle.querySelector('canvas'),lensC=lens.querySelector('canvas');
function fresnel(deg){const si=nWater*Math.sin(deg*rad);if(si>=1)return 1;const ci=Math.cos(deg*rad),ct=Math.sqrt(1-si*si);const rs=((nWater*ci-nAir*ct)/(nWater*ci+nAir*ct))**2;const rp=((nWater*ct-nAir*ci)/(nWater*ct+nAir*ci))**2;return (rs+rp)/2}
function line(ctx,a,b,color,width=7,opacity=1,dashed=false){ctx.save();ctx.strokeStyle=color;ctx.globalAlpha=opacity;ctx.lineWidth=width;ctx.lineCap='round';if(dashed)ctx.setLineDash([14,11]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();if(!dashed){const t=.57,x=a[0]+(b[0]-a[0])*t,y=a[1]+(b[1]-a[1])*t;ctx.translate(x,y);ctx.rotate(Math.atan2(b[1]-a[1],b[0]-a[0]));ctx.globalAlpha=Math.max(.85,opacity);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(20,0);ctx.lineTo(-13,-12);ctx.lineTo(-13,12);ctx.closePath();ctx.fill()}ctx.restore()}
function clear(c){const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);return x}
function endRay(x,y,theta,direction){const sx=Math.sin(theta*rad),sy=Math.cos(theta*rad)*direction;const toSide=(900-x)/Math.max(.001,sx),toEdge=direction<0?(y-35)/Math.max(.001,-sy):(540-y)/Math.max(.001,sy);const d=Math.min(toSide,toEdge);return [x+sx*d,y+sy*d]}
const splitAngles=[0,20,40,48.2,49];let splitCurrent=0,splitTarget=0,splitStart=0,splitFrom=0;
function paintSplit(){const ctx=clear(splitC),step=+split.dataset.step||0;if(step===0)return;const deg=splitCurrent,mid=[465,255],start=[mid[0]-Math.tan(deg*rad)*270,525],reflect=endRay(...mid,deg,1);const R=fresnel(deg);line(ctx,[465,45],[465,535],'#2b2b2b',2,.65,true);line(ctx,start,mid,'#e7a33d',10,.95);line(ctx,mid,reflect,'#c4161c',4+R*9,Math.max(.17,R));if(R<1){const out=Math.asin(Math.min(.999999,nWater*Math.sin(deg*rad)))/rad;line(ctx,mid,endRay(...mid,out,-1),'#327b9e',4+(1-R)*9,Math.max(.17,1-R))}ctx.beginPath();ctx.arc(...mid,10,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#20201e';ctx.lineWidth=3;ctx.stroke()}
function setSplit(){const step=+split.dataset.step||0,deg=splitAngles[step],R=step?fresnel(deg):0,pr=Math.round(R*100),pt=100-pr;splitFrom=splitCurrent;splitTarget=deg;splitStart=performance.now();document.querySelector('#split-angle').textContent=step?`水側の入射角 ${deg}°`:'水面に光を当てる';document.querySelector('#reflect-value').textContent=step?`約${pr}`:'—';document.querySelector('#refract-value').textContent=step?`約${pt}`:'—';document.querySelector('#reflect-bar').style.width=step?`${pr}%`:'0';document.querySelector('#refract-bar').style.width=step?`${pt}%`:'0';document.querySelector('#split-takeaway').textContent=['角度を変えて、光の行き先を見よう。','ほとんどは空気へ進む。','角度を大きくすると反射が増える。','反射と屈折がほぼ半分ずつ。','全反射。空気へ出る光はない。'][step];}
function paintAngle(){const ctx=clear(angleC),step=+angle.dataset.step||0;if(!step)return;const x=465,y=255;line(ctx,[x,45],[x,535],'#2b2b2b',2,.65,true);if(step===1){const water=40,air=Math.asin(nWater*Math.sin(water*rad))/rad;line(ctx,[x-Math.tan(water*rad)*260,515],[x,y],'#e7a33d',10,.95);line(ctx,[x,y],endRay(x,y,air,-1),'#327b9e',10,.95)}else{const air=40,water=Math.asin(Math.sin(air*rad)/nWater)/rad;line(ctx,[x-Math.tan(air*rad)*210,45],[x,y],'#e7a33d',10,.95);line(ctx,[x,y],endRay(x,y,water,1),'#327b9e',10,.95)}ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.strokeStyle='#20201e';ctx.lineWidth=3;ctx.stroke()}
function setAngle(){const step=+angle.dataset.step||0;document.querySelector('#angle-reading').textContent=['水と空気の境界に注目','水 → 空気','空気 → 水'][step];document.querySelector('#water-angle').textContent=['—','40°','約29°'][step];document.querySelector('#air-angle').textContent=['—','約59°','40°'][step];document.querySelector('#angle-takeaway').textContent=step?'空気側の角度が大きい。':'まず水から空気へ進む光を見よう。';paintAngle()}
function tick(now){if(!split.hidden){const t=Math.min(1,(now-splitStart)/650),e=t*t*(3-2*t);splitCurrent=splitFrom+(splitTarget-splitFrom)*e;paintSplit()}requestAnimationFrame(tick)}
for(const [el,fn] of [[split,setSplit],[angle,setAngle]])new MutationObserver(fn).observe(el,{attributes:true,attributeFilter:['data-step']});setSplit();setAngle();requestAnimationFrame(tick);
})();
