'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields=[['title','職種名'],['work','仕事内容'],['environment','職場環境'],['person','求める人物像'],['catch','キャッチコピー'],['place','紹介先企業・勤務地'],['pay','給与'],['hours','勤務時間'],['holiday','休日・休暇'],['benefits','福利厚生'],['selection','選考'],['trial','試用・研修期間']];
const samples=[{id:'SAMPLE-001',name:'条件がそろった求人',text:'職種名：受発注サポート事務\n仕事内容：注文内容の入力、納期の確認、メールでの問い合わせ対応\n職場環境：事務担当3名のチーム\n求める人物像：PCで文字入力ができる方\n紹介先企業・勤務地：架空企業A／架空市みどり町（デモ用所在地）\n給与：月給220,000円〜260,000円。固定残業代なし\n勤務時間：9:00〜18:00／休憩60分\n休日・休暇：土日祝休み\n福利厚生：社会保険完備、交通費支給（規定あり）\n選考：書類選考、面接1回\n試用・研修期間：3か月、同条件'}, {id:'SAMPLE-002',name:'給与が曖昧な求人',text:'職種名：倉庫内の検品スタッフ\n仕事内容：商品の検品、個数の確認、棚への収納\n職場環境：5名のチーム\n求める人物像：手順に沿って確認作業ができる方\n紹介先企業・勤務地：架空企業B／架空市あおば町（デモ用所在地）\n給与：経験による。詳細は面談で相談\n勤務時間：8:30〜17:30／休憩60分\n休日・休暇：土日休み\n福利厚生：社会保険完備\n選考：面接1回\n試用・研修期間：記載なし'}, {id:'SAMPLE-003',name:'情報が足りない求人',text:'職種名：カスタマーサポート\n仕事内容：メールへの返信、問い合わせ内容の記録\n求める人物像：丁寧な文章で案内できる方\n紹介先企業・勤務地：架空企業C／架空市しろい町（デモ用所在地）\n給与：時給1,400円\n勤務時間：10:00〜17:00／休憩60分\n休日・休暇：週休2日（シフト制）'}];
let store=[];try{store=JSON.parse(localStorage.getItem('saiyo-note-v1')||'[]');if(!Array.isArray(store))store=[]}catch{}let draft={id:samples[0].id,raw:samples[0].text,values:{},checks:{},locks:{},step:1}, screen='work', fieldIndex=0;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function persist(){try{localStorage.setItem('saiyo-note-v1',JSON.stringify(store));return true}catch{toast('保存できませんでした。ブラウザの保存設定を確認してください。');return false}}
function source(){const obj={};for(const line of draft.raw.split('\n')){const m=line.match(/^([^：:]+)[：:](.*)$/);if(m){const f=fields.find(f=>f[1]===m[1].trim());if(f)obj[f[0]]=m[2].trim()}}return obj}
function generate(){const s=source();for(const [k]of fields){if(draft.locks[k])continue;let val=s[k]||'';if(k==='catch')val=s.title?`${s.title}のお仕事`:'';if(k==='work'&&val)val=val.split(/[、,]/).map(v=>'・'+v.trim()).join('\n');draft.values[k]=val;draft.checks[k]=false}draft.step=2;fieldIndex=0;render();window.scrollTo(0,0)}
function issue(k){const s=source(),v=(draft.values[k]||'').trim();if(!s[k]&&k!=='catch')return '原文に記載がありません。元の求人票への追記・確認が必要です。';if(!v)return '内容が空欄です。';if(/記載なし|未定|要確認|面談で相談|経験による/.test(s[k]||''))return '条件が確定していません。元の求人票を確認してください。';if(k==='pay'&&!/[0-9０-９]/.test(s[k]||''))return '給与の金額を確認できません。';if(['place','pay','hours','holiday','benefits','trial'].includes(k)&&v!==(s[k]||''))return '原文の条件と一致しません。このデモでは条件項目を原文のまま保持します。';return ''}
function ready(){return fields.every(([k])=>!issue(k)&&draft.checks[k])}
function steps(){return '<ol class="steps">'+['取り込む','確認する','入力へ回す'].map((t,i)=>`<li class="${draft.step===i+1?'current':''}" ${draft.step===i+1?'aria-current="step"':''}><b>${i+1}</b>${t}</li>`).join('')+'</ol>'}
function heading(n,title,sub){return `<div class="heading-row"><div><h1 tabindex="-1">${title}</h1><p class="sub">${sub}</p></div>${title==='求人票を入れる'||title==='確認できた原稿を、入力へ。'?'<img class="desk-art" src="paper-tray.png" width="120" height="120" alt="書類を整えるトレーのAI生成イラスト">':''}</div>`}
function render(){document.querySelectorAll('.nav').forEach(e=>e.classList.remove('active'));$('#nav-'+screen).classList.add('active');$('#history-count').textContent=store.length;
 if(screen==='guide'){guide();return}if(screen==='history'){history();return}
 if(draft.step===1){$('#view').innerHTML=heading('','求人票を入れる','内容を整理して、ひとつずつ確認しましょう。')+steps()+`<div class="card import-card"><label class="label" for="raw">元の求人票 <span class="hint">架空サンプルを入力済みです</span></label><textarea id="raw" spellcheck="false">${esc(draft.raw)}</textarea><details class="more-options"><summary>サンプル変更・入力設定</summary><div class="samples">${samples.map((s,i)=>`<button class="chip ${draft.id===s.id?'selected':''}" data-sample="${i}">${s.name}</button>`).join('')}</div><label class="label" for="jobid">求人管理ID</label><input type="text" id="jobid" maxlength="100" value="${esc(draft.id)}"><p class="hint">「給与：…」の形式で入力。同じIDの新規原稿は重複保存しません。自由文のAI解析は本番構築の範囲です。</p></details><div id="import-error" role="alert" class="issue"></div><button class="primary wide" id="generate">内容を確認する →</button></div>`;
 document.querySelectorAll('[data-sample]').forEach(b=>b.onclick=()=>{const s=samples[+b.dataset.sample];draft={id:s.id,raw:s.text,values:{},checks:{},locks:{},step:1};render()});$('#generate').onclick=()=>{draft.id=$('#jobid').value.trim();draft.raw=$('#raw').value.trim();if(!draft.id||!draft.raw){$('#import-error').textContent='求人管理IDと元の求人票を入力してください。';return}const old=store.find(s=>s.id===draft.id);if(old&&draft.savedId!==draft.id){$('#import-error').textContent='この求人管理IDは保存済みです。「保存した原稿」から開くか、別のIDを使ってください。';return}generate()};return}
 if(draft.step===2){const [k,t]=fields[fieldIndex];const original=source()[k==='catch'?'title':k]||'記載なし';$('#view').innerHTML=heading('', '内容を確認する','原文と見比べて、問題なければ次へ。')+steps()+`<div class="review-meta"><span id="progress"></span><label class="jump">項目 <select id="field-select" aria-label="確認する項目">${fields.map(([key,title],i)=>`<option value="${i}" ${i===fieldIndex?'selected':''}>${i+1}. ${title}${issue(key)?'（要確認）':draft.checks[key]?' ✓':''}</option>`).join('')}</select></label></div><article class="card single-field" id="field-${k}"><div class="field-head"><h2>${t}</h2><span class="badge" id="badge-${k}"></span></div><div class="original"><span class="hint">元の求人票</span><p>${esc(original)}</p></div><label class="label" for="edit-${k}">掲載用の原稿</label><textarea id="edit-${k}" rows="3">${esc(draft.values[k])}</textarea><p class="issue" id="issue-${k}" role="alert"></p><details class="more-options"><summary>原文・修正の設定</summary><div class="field-options"><label><input type="checkbox" id="lock-${k}" ${draft.locks[k]?'checked':''}>修正内容を固定する</label></div><button class="quiet" id="regenerate">固定していない項目を整理し直す</button><details class="full-source"><summary>元の求人票をすべて見る</summary><pre>${esc(draft.raw)}</pre></details><button class="quiet" id="back-source">元の求人票を編集する</button></details><div class="focus-actions"><button class="secondary" id="previous" ${fieldIndex===0?'disabled':''}>戻る</button><button class="primary" id="confirm-field">確認して次へ →</button></div><button class="quiet" id="repair" hidden>元の求人票を修正する →</button></article><div class="under-actions"><button class="quiet" id="save">途中保存しておく</button><span class="hint" id="next-hint"></span></div>`;
 $('#edit-'+k).oninput=e=>{draft.values[k]=e.target.value;draft.checks[k]=false;status()};$('#lock-'+k).onchange=e=>draft.locks[k]=e.target.checked;$('#field-select').onchange=e=>{fieldIndex=+e.target.value;render()};$('#previous').onclick=()=>{fieldIndex--;render()};const editSource=()=>{draft.step=1;render();window.scrollTo(0,0)};$('#back-source').onclick=editSource;$('#repair').onclick=editSource;$('#regenerate').onclick=()=>{generate();toast('固定していない項目を整理しました。')};$('#save').onclick=()=>save();$('#confirm-field').onclick=()=>{if(issue(k))return;draft.checks[k]=true;if(ready()){draft.step=3;save(false)}else{const pending=fields.findIndex(([key],i)=>i>fieldIndex&&(!draft.checks[key]||issue(key)));fieldIndex=pending>=0?pending:fields.findIndex(([key])=>!draft.checks[key]||issue(key))}render();window.scrollTo(0,0)};status();return}
 $('#view').innerHTML=heading('03 / EXPORT','確認できた原稿を、入力へ。','項目ごとにコピーするか、まとめて書き出せます。求人サイトへの送信・公開は行いません。')+steps()+`<div class="banner ok">✓ 全12項目を確認済み。次は担当者が掲載先へ入力し、最終確認します。</div><div class="toolbar"><button class="secondary" id="edit-again">← 原稿を見直す</button><div><button class="secondary" id="download">JSONで保存</button> <button class="primary" id="copy-all">全文をコピー</button></div></div><div class="output">${fields.map(([k,t])=>`<article class="card"><div class="field-head"><h3>${t}</h3><button class="chip" data-copy="${k}" aria-label="${t}をコピー">コピー</button></div><p>${esc(draft.values[k])}</p></article>`).join('')}</div><div class="banner">Airワークとの接続はまだありません。自動入力は利用条件と管理画面の検証後に対応範囲を確定します。このJSONは本デモ独自の保存形式で、Airワークの取込形式ではありません。</div>`;
 $('#edit-again').onclick=()=>{draft.step=2;fieldIndex=0;render();window.scrollTo(0,0)};$('#copy-all').onclick=()=>copy(fields.map(([k,t])=>`${t}\n${draft.values[k]}`).join('\n\n'));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(draft.values[b.dataset.copy]));$('#download').onclick=()=>{const blob=new Blob([JSON.stringify({demo:true,id:draft.id,fields:draft.values},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='demo-job-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)};
}
function status(){const[k]=fields[fieldIndex],msg=issue(k),checked=fields.filter(([key])=>draft.checks[key]&&!issue(key)).length,n=fields.filter(([key])=>issue(key)).length;$('#issue-'+k).textContent=msg;$('#field-'+k).classList.toggle('problem',!!msg);$('#badge-'+k).textContent=msg?'要確認':draft.checks[k]?'確認済み':`${fieldIndex+1} / 12`;$('#badge-'+k).className='badge'+(msg?' warn':'');$('#progress').textContent=`${checked} / 12 項目を確認済み`;$('#confirm-field').disabled=!!msg;$('#confirm-field').textContent=msg?'条件の確認が必要です':checked===(draft.checks[k]?12:11)?'確認して原稿を完成する →':'確認して次へ →';$('#repair').hidden=!msg;$('#next-hint').textContent=n?`要確認 ${n}項目`:''}
function save(show=true){draft.savedId=draft.id;const row=JSON.parse(JSON.stringify({...draft,updated:new Date().toLocaleString('ja-JP'),status:ready()?'入力準備完了':'確認途中'}));const i=store.findIndex(s=>s.id===draft.id);if(i>=0)store[i]=row;else store.unshift(row);const ok=persist();$('#history-count').textContent=store.length;if(show&&ok)toast('このブラウザに保存しました。');return ok}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('コピーしました。')}catch{toast('コピーできませんでした。表示された原稿を選択してコピーしてください。')}}
function history(){$('#view').innerHTML=heading('YOUR DRAFTS','保存した原稿','続きはここから。保存はこの端末・このブラウザ内だけです。')+(store.length?store.map((s,i)=>`<article class="card saved-row"><div><h3>${esc(s.values.title||s.id)}</h3><span class="hint">${esc(s.id)} · ${esc(s.updated)}</span></div><span class="badge">${esc(s.status)}</span><button class="secondary" data-open="${i}">続きを開く →</button></article>`).join(''):'<div class="card empty"><h2>まだ保存した原稿はありません</h2><p>原稿の確認画面で「途中保存しておく」を押すと、ここに残ります。</p><button class="primary" id="start">原稿をつくる →</button></div>');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{draft=JSON.parse(JSON.stringify(store[+b.dataset.open]));draft.savedId=draft.id;draft.step=2;fieldIndex=Math.max(0,fields.findIndex(([k])=>!draft.checks[k]||issue(k)));screen='work';render()});if($('#start'))$('#start').onclick=()=>{screen='work';render()}}
function guide(){$('#view').innerHTML=heading('QUICK GUIDE','３ステップで、原稿づくり。','機能を覚えるより、画面の順番に沿って進める設計です。')+`<div class="card guide"><h2>1. 取り込む</h2><p>架空サンプルを選び、「内容を確認する」を押します。項目名と「：」で区切った文章を読み取ります。</p><h2>2. 確認する</h2><p>元の求人票と各項目を見比べます。足りない条件は推測しません。原文を追記するときも、架空のデータでお試しください。「給与が曖昧な求人」は要確認で止まります。</p><p>文章を編集したら「確認して次へ」を押します。「修正内容を固定」を選ぶと、整理し直しても編集内容が残ります。原文を変えた場合は、固定した条件に相違がないか再チェックします。</p><h2>3. 入力へ回す</h2><p>全項目を確認すると、項目ごとのコピー・全文コピー・JSON出力ができます。掲載先への公開操作は担当者が行う設計です。</p><h2>今回、実際に動くもの</h2><ul><li>項目名による原文の分解、定型整形、原文の表示</li><li>空欄・曖昧な条件のチェック、条件項目の完全一致チェック</li><li>編集・固定・個別確認・ブラウザ保存・同じIDの重複保存防止</li><li>項目別コピー・全文コピー・本デモ独自JSONの出力</li></ul><h2>本番で構築するもの</h2><p>AIによる自由な文章解析・生成、求人元との接続、Airワークへの入力、認証・共有・サーバー保存は未実装です。外部APIには情報を送信しません。自動入力の可否は規約と実画面を確認して判断します。</p><p>この体験版は原稿の正しさを保証するものではありません。原文の誤りや文章の意味まで自動判定せず、人の確認を残します。</p></div>`}
for(const k of ['work','history','guide'])$('#nav-'+k).onclick=()=>{if(screen==='work'&&draft.step===1&&$('#raw')){draft.raw=$('#raw').value;draft.id=$('#jobid').value}screen=k;render();window.scrollTo(0,0)};
$('#size').onclick=e=>{const on=document.documentElement.classList.toggle('large');e.target.setAttribute('aria-pressed',on);e.target.textContent=on?'標準の文字に戻す':'文字を大きく'};$('#motion').onclick=e=>{const on=document.documentElement.classList.toggle('stop');e.target.setAttribute('aria-pressed',on);e.target.textContent=on?'動きを戻す':'動きを止める'};render();
