const $=s=>document.querySelector(s), key='hitoyasumi-demo-v1';
const initial=()=>({posts:[{id:'a',author:'s1',name:'すず',tag:'今日の出来事',body:'帰り道、小さな花を見つけました。\nいつもより少しだけ、ゆっくり歩けた日。',liked:false,replies:[],reported:false,hidden:false},{id:'b',author:'s2',name:'ことり',tag:'聞いてほしい',body:'今日は予定をひとつ減らして、お茶の時間にしました。\nこんな日があってもいいかな。',liked:false,replies:[{name:'そよ',body:'ゆっくりできる時間、大事にしたいですね。'}],reported:false,hidden:false}],blocked:[],requests:[],history:[]});
let data;try{data=JSON.parse(localStorage.getItem(key))||initial();if(!Array.isArray(data.posts))data=initial()}catch{data=initial()}
let draft=null,timer;function tell(t){$('#status').textContent=t;clearTimeout(timer);timer=setTimeout(()=>$('#status').textContent='',5000)}
function save(){try{localStorage.setItem(key,JSON.stringify(data))}catch{tell('ブラウザ保存ができません。この画面内でのみお試しください。')}}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function btn(text,action,cls='sub'){const b=el('button',text,cls);b.type='button';b.onclick=action;return b}
function log(t){data.history.unshift(t);data.history=data.history.slice(0,30);save()}
function render(){const feed=$('#feed');feed.replaceChildren();const visible=data.posts.filter(p=>!p.hidden&&($('#filter').value==='すべて'||p.tag===$('#filter').value));if(!visible.length)feed.append(el('p','このタグの便りはまだありません。','panel'));
for(const p of visible){const card=el('article',undefined,'post'),head=el('div',undefined,'postHead');head.append(el('strong',p.name),el('span',p.tag,'tag'));card.append(head,el('p',p.body,'postText'));const actions=el('div',undefined,'actions');
actions.append(btn(p.liked?'♥ 気持ちを送りました':'♡ 優しい気持ちを送る',()=>{p.liked=!p.liked;save();render();tell(p.liked?'リアクションを保存しました':'リアクションを取り消しました')},p.liked?'liked':''));
const box=el('form',undefined,'replyBox');box.hidden=true;const rn=el('input');rn.placeholder='返信のニックネーム';rn.setAttribute('aria-label',p.name+'への返信ニックネーム');rn.required=true;rn.maxLength=20;const rb=el('textarea');rb.placeholder='仮の返信を書いてみる';rb.setAttribute('aria-label',p.name+'への返信本文');rb.required=true;rb.maxLength=300;rb.rows=2;const submit=el('button','返信をデモに保存','sub');submit.type='submit';box.append(rn,rb,submit);box.onsubmit=e=>{e.preventDefault();if(data.blocked.includes('visitor'))return tell('このブラウザの投稿者は利用制限中です。管理体験で解除できます。');if(!rn.value.trim()||!rb.value.trim())return tell('名前と返信を入力してください');p.replies.push({name:rn.value.trim(),body:rb.value.trim()});save();render();tell('返信をブラウザ内に保存しました')};
actions.append(btn('返信 '+p.replies.length,()=>{box.hidden=!box.hidden},''),btn(p.reported?'通報済み':'通報する',()=>{if(p.reported)return tell('管理体験に通報が記録されています');p.reported=true;log(p.name+'の投稿を通報');render();tell('通報を管理体験に保存しました。外部には送信されません。')},''));card.append(actions);p.replies.forEach(r=>card.append(el('p',r.name+'：'+r.body,'reply')));card.append(box);feed.append(card)}renderAdmin()}
function renderAdmin(){const root=$('#moderation');root.replaceChildren();data.posts.forEach(p=>{const row=el('div',undefined,'modRow');row.append(el('strong',p.name+' ／ '+(p.reported?'通報あり':'通報なし')),el('p',p.body.slice(0,70)),el('p',p.hidden?'非表示（削除体験・復元可能）':'表示中'));row.append(btn(p.hidden?'投稿を復元':'投稿を非表示',()=>{p.hidden=!p.hidden;log(p.name+'：'+(p.hidden?'非表示':'復元'));render()}));const blocked=data.blocked.includes(p.author);row.append(btn(blocked?'利用制限を解除':'投稿者を利用制限',()=>{data.blocked=blocked?data.blocked.filter(x=>x!==p.author):[...data.blocked,p.author];log(p.name+'：利用制限'+(blocked?'解除':'設定'));render();tell(p.author==='visitor'&&!blocked?'このブラウザからの新規投稿・返信を制限しました':'デモ内の投稿者IDに制限を反映しました')}));if(p.reported)row.append(btn('通報を確認済みにする',()=>{p.reported=false;log(p.name+'：通報確認済み');render()}));root.append(row)});$('#requestList').replaceChildren(...(data.requests.length?data.requests:['まだ届いていません']).map(t=>el('li',t)));$('#history').replaceChildren(...(data.history.length?data.history:['まだ操作はありません']).map(t=>el('li',t)))}
$('#message').oninput=()=>$('#counter').textContent=$('#message').value.length+' / 1000';
$('#postForm').onsubmit=e=>{e.preventDefault();if(data.blocked.includes('visitor'))return tell('このブラウザの投稿者は利用制限中です。管理体験から解除できます。');const name=$('#nickname').value.trim(),body=$('#message').value.trim();if(!name||!body)return tell('名前と本文を入力してください');draft={id:String(Date.now()),author:'visitor',name,body,tag:$('input[name=tag]:checked').value,liked:false,replies:[],reported:false,hidden:false};$('#previewText').textContent=name+' ／ '+draft.tag+'\n\n'+body;$('#postForm').hidden=true;$('#preview').hidden=false};
$('#editPost').onclick=()=>{$('#preview').hidden=true;$('#postForm').hidden=false;draft=null};
$('#confirmPost').onclick=()=>{if(!draft)return;if(data.blocked.includes('visitor'))return tell('利用制限中です');data.posts.unshift(draft);draft=null;save();$('#postForm').reset();$('#counter').textContent='0 / 1000';$('#postForm').hidden=false;$('#preview').hidden=true;$('#filter').value='すべて';render();tell('投稿をブラウザ内に保存しました。外部には送信されません。')};
$('#filter').onchange=render;$('#adminToggle').onclick=()=>{$('#admin').hidden=!$('#admin').hidden;$('#adminToggle').textContent=$('#admin').hidden?'管理体験':'管理体験を閉じる';if(!$('#admin').hidden)$('#admin').scrollIntoView()};
$('#requestForm').onsubmit=e=>{e.preventDefault();const t=$('#requestText').value.trim();if(!t)return;data.requests.unshift(t);save();$('#requestText').value='';renderAdmin();tell('要望をブラウザ内の管理体験に保存しました')};
$('#reset').onclick=()=>$('#resetConfirm').hidden=false;$('#resetNo').onclick=()=>$('#resetConfirm').hidden=true;$('#resetYes').onclick=()=>{data=initial();draft=null;save();$('#postForm').reset();$('#postForm').hidden=false;$('#preview').hidden=true;$('#counter').textContent='0 / 1000';$('#filter').value='すべて';$('#resetConfirm').hidden=true;render();tell('デモを初期状態に戻しました')};render();
