const $=s=>document.querySelector(s), E=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seed=[{id:1,name:'展示会サイトの公開準備',client:'あおば企画［架空］',owner:'担当A',status:'確認待ち',date:'2026-09-22',note:'原稿の最終確認を依頼済み。次はスマホ表示の確認。',tasks:[['原稿整理',true],['スマホ表示を確認',false],['公開承認を記録',false]]},{id:2,name:'秋のカタログ制作',client:'こもれび製作所［架空］',owner:'担当B',status:'進行中',date:'2026-09-25',note:'写真3点の差し替え待ち。承認後に版下へ進む。',tasks:[['構成確認',true],['写真差し替え',false]]},{id:3,name:'導入ヒアリング',client:'みなも商会［架空］',owner:'担当A',status:'準備中',date:'2026-09-20',note:'現行の管理項目を整理する。',tasks:[['質問項目を準備',false]]}];
let db;try{db=JSON.parse(localStorage.getItem('kito-v1'))}catch{}if(!db||!Array.isArray(db.jobs))db={jobs:structuredClone(seed),logs:[]};let view='today',undo=null,selected=null;
function save(){try{localStorage.setItem('kito-v1',JSON.stringify(db))}catch{$('#announce').textContent='この環境では保存できません。画面内の操作のみ反映しています。'}}
function log(text){db.logs.unshift({text,time:new Date().toLocaleString('ja-JP')});save()}
function readonly(){return $('#role').value==='閲覧のみ'}
function mutate(fn,text){if(readonly())return;undo=structuredClone(db);fn();log(text);render();$('#announce').textContent=text+'（このブラウザ内）';}
function visible(){return db.jobs.filter(j=>(j.name+j.client).includes($('#search').value)&&($('#filter').value==='すべて'||j.status===$('#filter').value))}
function render(){const wait=db.jobs.filter(j=>j.status==='確認待ち').length;$('#metrics').innerHTML=[['進行している案件',db.jobs.filter(j=>j.status!=='完了').length],['確認を待っている案件',wait],['残っているタスク',db.jobs.flatMap(j=>j.tasks).filter(t=>!t[1]).length]].map(([s,n])=>`<div class="metric"><span>${s}</span><strong>${n}<small> 件</small></strong></div>`).join('');$('#new').disabled=readonly();$('#sample').disabled=readonly();$('#reset').disabled=readonly();
const titles={today:['今日の仕事が、<br>すっと見える。','期限と担当、次の一手をひとつの場所に。'],projects:['案件の流れを、<br>チームの共通言語に。','相談から完了まで。担当と次の作業を残します。'],clients:['取引先から、<br>仕事をたどる。','関連案件と対応メモを同じ画面で確認。'],files:['資料のありかを、<br>迷わず探す。','このデモでは資料名と関連案件のみ表示します。実ファイルは保存しません。'],history:['変更の理由も、<br>引き継げる。','画面上の変更記録です。本番の監査ログではありません。']};$('#heading').innerHTML=titles[view][0];$('#intro').textContent=titles[view][1];
let html='';if(view==='history')html=(undo?'<div class="toolbar"><button id="undo">直前の変更を取り消す</button></div>':'')+db.logs.map(l=>`<div class="log"><small>${E(l.time)}</small><div>${E(l.text)}</div></div>`).join('');else if(view==='files')html=visible().map(j=>`<div class="row"><div><h3>${E(j.name)}・要件メモ</h3><p>架空資料 / メタ情報のみ</p></div><span>${E(j.client)}</span><span>更新確認待ち</span><button data-id="${j.id}">関連案件を見る</button></div>`).join('');else if(view==='clients')html=[...new Set(visible().map(j=>j.client))].map(c=>`<div class="row"><h3>${E(c)}</h3><span>関連 ${db.jobs.filter(j=>j.client===c).length} 件</span><span>連絡先未登録</span><button data-id="${db.jobs.find(j=>j.client===c).id}">案件を開く</button></div>`).join('');else html=visible().sort((a,b)=>a.date.localeCompare(b.date)).map(j=>`<div class="row reveal"><div><h3>${E(j.name)}</h3><p>${E(j.client)} / ${E(j.owner)}</p></div><span>期限 ${E(j.date)}</span><span class="tag ${j.status==='確認待ち'?'wait':''}">${E(j.status)}</span><button data-id="${j.id}">詳細を見る</button></div>`).join('');$('#content').innerHTML=html||'<p class="empty">該当するデータはありません。</p>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openJob(+b.dataset.id));if($('#undo'))$('#undo').onclick=()=>{if(readonly())return;db=undo;undo=null;log('直前の変更を取り消しました');render()};if($('#undo'))$('#undo').disabled=readonly();}
function openJob(id){selected=id;const j=db.jobs.find(x=>x.id===id)||{name:'',client:'',owner:'担当A',status:'準備中',date:'',note:'',tasks:[]};$('#detail-content').innerHTML=`<p class="eyebrow">PROJECT / ${id||'NEW'}</p><h2>${id?'案件の確認・編集':'案件を追加'}</h2><form class="edit" id="edit"><label>案件名<input name="name" required maxlength="80" value="${E(j.name)}"></label><label>取引先（架空）<input name="client" required maxlength="80" value="${E(j.client)}"></label><label>担当者<select name="owner">${['担当A','担当B'].map(x=>`<option ${x===j.owner?'selected':''}>${x}</option>`).join('')}</select></label><label>状態<select name="status">${['準備中','進行中','確認待ち','完了'].map(x=>`<option ${x===j.status?'selected':''}>${x}</option>`).join('')}</select></label><label>期限<input type="date" name="date" required value="${j.date}"></label><label>引き継ぎメモ<textarea name="note" maxlength="500">${E(j.note)}</textarea></label><div class="subtasks">${j.tasks.map((t,i)=>`<label><input type="checkbox" name="task${i}" ${t[1]?'checked':''}> ${E(t[0])}</label>`).join('')}</div><button class="primary" ${readonly()?'disabled':''}>内容を保存する</button><p>保存先はこのブラウザのみです。</p></form>`;if(readonly())$('#edit').querySelectorAll('input,select,textarea').forEach(el=>el.disabled=true);$('#edit').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(!String(f.get('name')).trim()||!String(f.get('client')).trim())return;mutate(()=>{const next={id:id||Date.now(),name:f.get('name').trim(),client:f.get('client').trim(),owner:f.get('owner'),status:f.get('status'),date:f.get('date'),note:f.get('note'),tasks:j.tasks.map((t,i)=>[t[0],f.has('task'+i)])};if(id)db.jobs[db.jobs.findIndex(x=>x.id===id)]=next;else db.jobs.push(next)},id?'案件と引き継ぎを更新':'案件を追加');$('#detail').close()};$('#detail').showModal()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#search').oninput=render;$('#filter').onchange=render;$('#role').onchange=render;$('#new').onclick=()=>openJob(null);$('#close').onclick=()=>$('#detail').close();$('#motion').onclick=()=>{document.body.classList.toggle('still');$('#motion').textContent=document.body.classList.contains('still')?'動きを再開':'動きを停止'};
$('#export').onclick=()=>{const safe=x=>{let v=String(x);if(/^[=+@-]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"'};const rows=[['案件名','取引先','担当','状態','期限','引き継ぎ'],...db.jobs.map(j=>[j.name,j.client,j.owner,j.status,j.date,j.note])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));a.download='kito-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);$('#announce').textContent='架空案件のCSVを出力しました。'};
$('#sample').onclick=()=>{$('#detail-content').innerHTML='<p class="eyebrow">IMPORT PREVIEW</p><h2>取込前に、内容を確認。</h2><p>サンプルCSV 1件：くるみ工房［架空］ / 新サービス案内 / 担当B / 準備中 / 2026-10-01</p><p>同名案件がある場合は追加しません。任意CSVの取込は本番実装時に項目マッピングを設計します。</p><button class="primary" id="confirm-import">サンプル1件を追加</button>';$('#detail').showModal();$('#confirm-import').onclick=()=>{if(db.jobs.some(x=>x.name==='新サービス案内')){$('#announce').textContent='同名案件があるため追加しませんでした。'}else mutate(()=>db.jobs.push({id:Date.now(),name:'新サービス案内',client:'くるみ工房［架空］',owner:'担当B',status:'準備中',date:'2026-10-01',note:'サンプルCSVから追加',tasks:[]}),'サンプルを1件取り込み');$('#detail').close()}};
$('#reset').onclick=()=>{$('#detail-content').innerHTML='<h2>架空データを初期化しますか？</h2><p>このブラウザでの変更のみを初期状態に戻します。</p><button id="confirm-reset">初期化する</button>';$('#detail').showModal();$('#confirm-reset').onclick=()=>{db={jobs:structuredClone(seed),logs:[]};undo=null;save();render();$('#detail').close();$('#announce').textContent='初期化しました。'}};render();
