const products=[{id:'blue',name:'コットン オーバーシャツ',category:'シャツ',price:8800,color:'スレートブルー',position:'25% 40%'},{id:'white',name:'レギュラーカラー シャツ',category:'シャツ',price:7700,color:'オフホワイト',position:'90% 60%'},{id:'denim',name:'ストレート デニム',category:'パンツ',price:11000,color:'インディゴ',position:'85% 90%'}];
const yen=n=>'¥'+n.toLocaleString('ja-JP');let bag=[];try{bag=JSON.parse(localStorage.getItem('ordin-demo-bag')||'[]');if(!Array.isArray(bag))bag=[];bag=bag.filter(x=>products.some(p=>p.id===x.id)&&['S','M','L'].includes(x.size)&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=5)}catch(e){bag=[]}
const count=()=>document.querySelector('#count').textContent=bag.reduce((a,x)=>a+x.qty,0);const save=()=>{try{localStorage.setItem('ordin-demo-bag',JSON.stringify(bag))}catch(e){}count()};count();
const card=p=>`<a class="item" href="product.html?id=${p.id}"><div class="photo"><img src="${p.id}.webp" alt="${p.name}を含む架空スタイリング・AI生成" loading="lazy"></div><h3>${p.name}</h3><p>${p.color} / ${yen(p.price)} 税込・仮価格</p><small>AI生成・架空の商品イメージ</small></a>`;
if(document.querySelector('#featured'))document.querySelector('#featured').innerHTML=products.map(card).join('');
const catalog=document.querySelector('#catalog');if(catalog){const render=()=>{let list=products.filter(p=>(document.querySelector('#category').value==='all'||p.category===document.querySelector('#category').value)&&(p.name+p.color).includes(document.querySelector('#search').value.trim()));if(document.querySelector('#sort').value==='low')list.sort((a,b)=>a.price-b.price);catalog.innerHTML=list.length?list.map(card).join(''):'<p>該当する商品がありません。検索語やカテゴリーを変更してください。</p>';document.querySelector('#result').textContent=list.length+'点のサンプル商品'};['search','category','sort'].forEach(id=>document.getElementById(id).addEventListener('input',render));render()}
if(document.querySelector('#add-form')){const p=products.find(x=>x.id===new URLSearchParams(location.search).get('id'))||products[0];document.querySelector('#product-name').textContent=p.name;document.querySelector('#product-color').textContent=p.color;document.querySelector('#product-price').textContent=yen(p.price)+'（税込・仮価格）';document.querySelector('#product-img').src=p.id+'.webp';document.querySelector('#add-form').addEventListener('submit',e=>{e.preventDefault();const size=document.querySelector('#size').value,qty=Number(document.querySelector('#qty').value);if(!['S','M','L'].includes(size)||!Number.isInteger(qty)||qty<1||qty>5)return;const old=bag.find(x=>x.id===p.id&&x.size===size);if(old&&old.qty+qty>5){document.querySelector('#added').textContent='同じ商品・サイズは5点までです。バッグで数量を確認してください。';return}if(old)old.qty+=qty;else bag.push({id:p.id,size,qty});save();document.querySelector('#added').textContent='デモのバッグに追加しました。注文は送信されていません。'})}
const cart=document.querySelector('#cart');if(cart){const render=()=>{cart.innerHTML=bag.length?bag.map((x,i)=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-row"><div><h2>${p.name}</h2><p>${p.color} / サイズ ${x.size}<br>${yen(p.price)} × ${x.qty}</p><button class="remove" data-remove="${i}">この商品を削除</button></div><label>数量<select aria-label="${p.name} ${x.size}の数量" data-qty="${i}">${[1,2,3,4,5].map(n=>`<option ${x.qty===n?'selected':''}>${n}</option>`).join('')}</select></label></div>`}).join(''):'<p>バッグは空です。商品一覧からお選びください。</p>';document.querySelector('#total').textContent='商品合計 '+yen(bag.reduce((a,x)=>a+products.find(p=>p.id===x.id).price*x.qty,0))+'（税込・仮価格）';cart.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{bag.splice(Number(b.dataset.remove),1);save();render()}));cart.querySelectorAll('[data-qty]').forEach(s=>s.addEventListener('change',()=>{bag[Number(s.dataset.qty)].qty=Number(s.value);save();render()}))};render()}
document.querySelector('#motion').addEventListener('click',e=>{const stopped=document.body.classList.toggle('stop');e.currentTarget.textContent=stopped?'動きを再開する':'動きを止める';e.currentTarget.setAttribute('aria-pressed',String(stopped))});
