const main=document.querySelector('#main'),detail=document.querySelector('#detail');
const image='<img src="assets/atelier-ai.jpg" alt="雲に浮かぶ青いアトリエ。AI生成の架空イラスト" width="1536" height="1024">';
const cta='<section class="cta"><p class="eyebrow">LET’S MAKE SOMETHING LOVELY.</p><h2>まだ、ぼんやりした<br>イメージでも。</h2><p>つくりたいものを選んで、相談の流れを体験してみませんか。</p><a class="button" href="#contact">相談の体験へ ↗</a></section>';
const heading=(en,jp,desc)=>`<section class="pagehead"><a class="crumb" href="#home">HOME / ${en.toUpperCase()}</a><p class="display">${en}<span>✦</span></p><h1>${jp}</h1><p>${desc}</p></section>`;
let estimate=null;
const views={
home:()=>`<section class="hero"><div class="hero-copy"><p class="eyebrow">YOUR LITTLE WORLD, BEAUTIFULLY MADE.</p><h1>あなたの「好き」に、<br><em>とっておきの</em><br>かたちを。</h1><p>イラストも、配信の世界も。<br>小さなアイデアをひとつずつ、眺めて、選んで。</p><a class="button" href="#gallery">作品サンプルを見てみる ↗</a><small>架空のクリエイタースタジオ / 提案用コンセプト</small></div><figure>${image}<figcaption>BLUE ATELIER — AI CONCEPT ART</figcaption><span class="seal">Made of<br><i>little dreams.</i></span></figure></section><div class="ticker">ILLUSTRATION &nbsp; ✦ &nbsp; YOUR OWN WORLD</div><section class="intro"><p class="eyebrow">WELCOME TO OUR LITTLE ATELIER</p><h2>ここは、アイデアの<br>小さな待ち合わせ場所。</h2><p>「こんな雰囲気が好き」「こんな場所で使いたい」。<br>作品と制作メニューから、あなたに近い世界を探してください。</p></section><section class="wrap"><div class="sectiontitle"><div><p class="eyebrow">01 / EXPLORE</p><h2>何をつくりましょう？</h2></div><a href="#menu">料金の目安を見る ↗</a></div><div class="services"><a href="#gallery"><b>01</b><span>Illustration</span><h3>イラスト</h3><p>アイコンやキービジュアル。<br>一枚の絵から、世界を広げる。</p><i>作品を見る ↗</i></a><a href="#gallery"><b>02</b><span>Stream design</span><h3>配信デザイン</h3><p>配信背景や画面まわり。<br>居心地のよい、小さなステージ。</p><i>作品を見る ↗</i></a><a href="#menu"><b>03</b><span>Your idea</span><h3>まずは内容を整理</h3><p>用途とサイズ、追加条件を確認。<br>基本料金だけで決めない相談へ。</p><i>メニューを見る ↗</i></a></div></section><section class="feature wrap"><figure>${image}<figcaption>AIによる架空の作品サンプル</figcaption></figure><div><p class="eyebrow">02 / PICK UP A WORLD</p><h2>ふわりと青い、<br>空のアトリエ。</h2><p>作品の雰囲気だけでなく、使い道や必要な仕様も、一緒に確認できるギャラリーです。</p><a href="#gallery">サンプルの制作意図を見る ↗</a></div></section><section class="wrap"><p class="eyebrow">03 / BEFORE YOU ASK</p><h2>迷ったら、この順番で。</h2><ol class="steps"><li><b>01</b><h3>雰囲気を探す</h3><p>制作物・テイストで絞り込み。</p></li><li><b>02</b><h3>料金の条件を知る</h3><p>基本範囲とオプションを分けて確認。</p></li><li><b>03</b><h3>相談内容をまとめる</h3><p>選択内容を引き継いで確認画面へ。</p></li></ol></section>${cta}`,
gallery:()=>heading('Gallery','好きな世界を、見つけよう。','AI生成のコンセプト例です。実際の制作実績ではありません。')+`<section class="wrap"><div class="filters"><label>制作物<select id="type"><option value="all">すべて</option><option value="illustration">イラスト</option><option value="stream">配信背景</option></select></label><label>テイスト<select id="mood"><option value="all">すべて</option><option value="soft">やわらかい</option><option value="cool">クール</option></select></label><button id="clearFilters">選択をリセット</button></div><p id="resultCount" role="status"></p><div id="works" class="workgrid"></div><p id="empty" hidden>条件に合うサンプルはありません。条件を変えるか、リセットしてください。</p><p class="fine">現在は1作品を登録した操作サンプルです。受託実績や対応作風の実績数を示すものではありません。</p></section>${cta}`,
menu:()=>heading('Menu','料金は、条件とセットで。','金額は操作体験用の仮料金です。実際のサービス価格ではありません。')+`<section class="wrap"><div class="pricecards">${[['ILLUSTRATION','イラスト','8,000','1点・背景なし・ラフ1案'],['STREAM BACKGROUND','配信背景','12,000','静止画1点・1サイズ']].map(x=>`<article><p class="eyebrow">${x[0]}</p><h2>${x[1]}</h2><p class="price">¥${x[2]}<span>〜 / 仮・税込基本料金</span></p><dl><dt>基本範囲</dt><dd>${x[3]}</dd><dt>修正</dt><dd>ラフ段階2回の設定例</dd><dt>納品</dt><dd>PNG / 個人利用想定</dd></dl><details><summary>追加条件を確認</summary><p>背景・差分・追加修正・商用利用等は個別確認。著作権譲渡・特急対応はこの概算に含みません。</p></details></article>`).join('')}</div><div class="calculator"><div><p class="eyebrow">TRY A ROUGH ESTIMATE</p><h2>おおよその条件を<br>組み立てる。</h2><p>仮料金の計算デモです。<br>注文や契約は成立しません。</p></div><form id="estimate"><label>制作物<select id="product"><option value="illustration">イラスト / 8,000円</option><option value="stream">配信背景 / 12,000円</option></select></label><label class="check"><input id="background" type="checkbox">描き込み追加 / ＋3,000円（仮）</label><label class="check"><input id="revision" type="checkbox">修正1回追加 / ＋1,000円（仮）</label><div class="total"><span>仮の概算（税込）</span><output id="total" aria-live="polite">¥8,000</output></div><p class="fine">内容・使用用途により正式見積りは変動します。著作権譲渡・特急・商用条件は別途確認。</p><button class="button" type="submit">この内容で相談を体験 ↗</button><button type="reset">選び直す</button></form></div></section>`,
guide:()=>heading('Guide','はじめてのご相談へ。','最初からすべて決まっていなくても。必要な条件をひとつずつ整理します。')+`<section class="wrap"><ol class="steps"><li><b>01</b><h3>希望を整理</h3><p>制作物・使う場所・サイズ・希望時期を確認。</p></li><li><b>02</b><h3>範囲と見積りを確認</h3><p>料金・修正・使用許可・納期の起点を明文化。</p></li><li><b>03</b><h3>制作・確認・納品</h3><p>ラフ確認の工程と修正範囲を決めてから着手。</p></li></ol><div class="notice"><h2>相談しただけでは、依頼確定になりません。</h2><p>このデモは外部送信されません。本制作では、正式な見積りと条件の合意を依頼確定の手順に含めます。</p></div><div class="faq"><h2>気になることを、先に。</h2>${[['基本料金だけで制作できますか？','背景・差分・利用条件などは追加確認が必要です。ここにある金額は仮設定です。'],['商用利用や著作権譲渡は含みますか？','含むとは扱いません。使用目的と権利の範囲を個別に確認する想定です。'],['納期はいつから数えますか？','素材・条件・着手日を合意した時点を基準に確認します。このデモは納期を確約しません。'],['このページから実際に依頼できますか？','できません。選択と確認の操作体験のみで、送信・契約・決済は未接続です。']].map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section>${cta}`,
contact:()=>heading('Contact','相談の前に、小さな整理を。','個人情報の入力は不要です。選択内容を確認する操作だけを体験できます。')+`<section class="wrap contact"><div><p class="eyebrow">YOUR IDEA</p><h2>つくりたいものを、<br>聞かせてください。</h2><p>○ 相談可能（仮の表示）</p><p>受付状況は全画面で共通表示。<br>このデモは実際の相談を受け付けません。</p><a href="#guide">依頼の流れ・よくある質問 ↗</a></div><div><form id="consult"><label>相談の種類<select id="purpose"><option>見積りの相談</option><option>制作内容の相談</option></select></label><label>希望の制作物<select id="want"><option value="illustration">イラスト</option><option value="stream">配信背景</option><option value="other">まだ決まっていない</option></select></label><label>イメージ<select id="taste"><option>やわらかい</option><option>クール</option><option>相談して決めたい</option></select></label><div id="carried" class="notice" hidden></div><p class="fine">個人情報は収集しません。未接続の操作体験です。</p><button type="submit" class="button">内容を確認する ↗</button></form><section id="confirmation" hidden tabindex="-1"><p class="eyebrow">PREVIEW ONLY</p><h2>選択内容の確認</h2><div id="summary"></div><p class="notice">送信されていません。このデモには送信機能がありません。</p><button id="edit" class="button">選び直す ←</button></section></div></section>`
};
const $=s=>document.querySelector(s),money=n=>'¥'+n.toLocaleString('ja-JP');
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.08});
function render(){const key=location.hash.slice(1)||'home';main.innerHTML=(views[key]||views.home)();document.title=(['home','gallery','menu','guide','contact'].includes(key)?key:'home')+' | atelier Lune. 架空デモ';document.querySelectorAll('header nav a').forEach(a=>{if(a.hash==='#'+key)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});detail.close();window.scrollTo({top:0,behavior:'instant'});observer.disconnect();main.querySelectorAll('.intro,.services,.feature,.steps,.cta').forEach(el=>{el.classList.add('scroll-reveal');observer.observe(el)});
if(key==='gallery'){const filter=()=>{let shown=($('#type').value==='all'||$('#type').value==='illustration')&&($('#mood').value==='all'||$('#mood').value==='soft');$('#resultCount').textContent=shown?'1件のサンプル':'0件のサンプル';$('#empty').hidden=shown;$('#works').innerHTML=shown?`<button class="work" id="openWork">${image}<h3>空のアトリエ</h3><small>イラスト / やわらかい / 青・アイボリー</small><span>作品のコンセプトを見る ↗</span></button>`:'';if(shown)$('#openWork').onclick=()=>{$('#detailBody').innerHTML=image+'<h2>空のアトリエ</h2><p>AI生成コンセプト。雲の上の小さなアトリエを、青とアイボリーで表現した架空の作品です。</p><dl><dt>用途例</dt><dd>サイトのキービジュアル</dd><dt>モチーフ</dt><dd>画材・月・花・雲</dd><dt>参考範囲</dt><dd>世界観を共有するための例。実制作プランや納品実績ではありません。</dd></dl>';detail.showModal()}};$('#type').onchange=filter;$('#mood').onchange=filter;$('#clearFilters').onclick=()=>{$('#type').value='all';$('#mood').value='all';filter()};filter()}
if(key==='menu'){const calculate=()=>({product:$('#product').value,background:$('#background').checked,revision:$('#revision').checked,total:($('#product').value==='stream'?12000:8000)+($('#background').checked?3000:0)+($('#revision').checked?1000:0)});$('#estimate').onchange=()=>$('#total').textContent=money(calculate().total);$('#estimate').onreset=()=>{estimate=null;requestAnimationFrame(()=>$('#total').textContent=money(calculate().total))};$('#estimate').onsubmit=e=>{e.preventDefault();estimate=calculate();location.hash='contact'}}
if(key==='contact'){const carried=$('#carried');if(estimate){$('#want').value=estimate.product;carried.hidden=false;carried.textContent=`引き継いだ仮概算：${money(estimate.total)}（税込）。描き込み追加：${estimate.background?'あり':'なし'}、修正追加：${estimate.revision?'あり':'なし'}。`;}$('#want').onchange=()=>{if(estimate&&$('#want').value!==estimate.product){estimate=null;carried.hidden=false;carried.textContent='制作物を変更したため、前の仮概算を解除しました。料金画面から再計算できます。'}};$('#consult').onsubmit=e=>{e.preventDefault();$('#summary').textContent=[$('#purpose').value,$('#want').selectedOptions[0].text,$('#taste').value,estimate?`仮概算 ${money(estimate.total)}（税込）`:'概算なし'].join(' / ');$('#consult').hidden=true;$('#confirmation').hidden=false;$('#confirmation').focus()};$('#edit').onclick=()=>{$('#confirmation').hidden=true;$('#consult').hidden=false;$('#purpose').focus()}}}
$('#closeDetail').onclick=()=>detail.close();detail.addEventListener('click',e=>{if(e.target===detail)detail.close()});$('#motion').onclick=()=>{let stopped=document.body.classList.toggle('paused');$('#motion').setAttribute('aria-pressed',String(stopped));$('#motion').textContent=stopped?'動きを再開する':'動きを止める'};window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true})});render();
