'use strict';
const $=id=>document.getElementById(id),key='komorebiNotes5316038';
const initial=[{title:'はじめに・教材の読み方',words:'教材 読む 順番 最初 はじめ 初心者',text:'【架空の操作説明用教材】\n最初に「はじめに」を読み、次に関心のあるテーマを選ぶ構成です。全ページを順番に読む必要はない、という仮の案内です。実際の教材ルールではありません。'},{title:'観察ノート・遊びの記録',words:'遊び 記録 観察 ノート メモ',text:'【架空の操作説明用教材】\n遊びの記録欄には、日付・使ったもの・気づいたことを書く、というサンプルです。お子さまの発達を判定するための資料ではありません。'},{title:'更新のお知らせを読む',words:'更新 週 追加 新しい お知らせ',text:'【架空の操作説明用教材】\n新しい教材は更新一覧から探せる、という仮の運用例です。参照した教材の版を表示して、更新後の内容か確認できるようにします。'}];
let data={docs:structuredClone(initial),pending:[],version:1};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Array.isArray(saved.docs)&&saved.docs.every(d=>typeof d.title==='string'&&typeof d.text==='string'&&typeof d.words==='string')&&Array.isArray(saved.pending))data=saved}catch{}
const persist=()=>{try{localStorage.setItem(key,JSON.stringify(data));return true}catch{return false}};
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function tabs(name){for(const p of document.querySelectorAll('.panel'))p.hidden=p.id!==name;for(const b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-pressed',String(b.dataset.tab===name))}if(name==='pending')renderPending()}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>tabs(b.dataset.tab);
$('motion').onclick=()=>{const on=document.body.classList.toggle('still');$('motion').textContent=on?'動きを再開':'動きを止める';$('motion').setAttribute('aria-pressed',String(on))};
function refresh(){const old=$('docselect').value;$('docselect').replaceChildren();data.docs.forEach((d,i)=>{const o=element('option',d.title);o.value=i;$('docselect').append(o)});if(data.docs[old])$('docselect').value=old;$('version').textContent=data.version;$('count').textContent=data.pending.length;loadDoc()}
function loadDoc(){const d=data.docs[Number($('docselect').value)];if(!d)return;$('doctitle').value=d.title;$('keywords').value=d.words;$('doctext').value=d.text}
$('docselect').onchange=loadDoc;
$('save').onclick=()=>{const title=$('doctitle').value.trim(),text=$('doctext').value.trim(),words=$('keywords').value.trim();if(!title||!text||!words){$('editorStatus').textContent='教材名・探す言葉・本文をすべて入力してください。';return}data.docs[Number($('docselect').value)]={title,text,words};data.version++;const stored=persist();refresh();$('editorStatus').textContent=`教材版 ${data.version} に更新しました。`+(stored?'このブラウザに保存しました。':'保存できなかったため、この画面を閉じると消えます。')};
$('add').onclick=()=>{data.docs.push({title:'新しい仮教材',words:'新規',text:'仮の内容をここに入力してください。'});refresh();$('docselect').value=data.docs.length-1;loadDoc();$('editorStatus').textContent='編集後「更新を反映」で保存してください。'};
let resetArmed=false;$('reset').onclick=()=>{if(!resetArmed){resetArmed=true;$('reset').textContent='もう一度押すと初期化';$('editorStatus').textContent='教材と未回答ノートのブラウザ保存を初期化します。';return}data={docs:structuredClone(initial),pending:[],version:1};persist();refresh();renderPending();$('answer').replaceChildren(element('p','初期データへ戻しました。質問を入力してください。'));resetArmed=false;$('reset').textContent='初期データへ戻す';$('editorStatus').textContent='初期データに戻しました。'};
function search(q){q=q.trim();if(!q)return;const box=$('answer');box.replaceChildren();const unsafe=/発熱|けいれん|呼吸|診断|薬|病気|死|虐待/.test(q);const found=unsafe?[]:data.docs.map(d=>({d,score:d.words.split(/\s+/).filter(w=>w&&q.includes(w)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,2);box.append(element('h3',found.length?'関連する教材の抜粋':'この仮教材だけでは答えられません'));box.append(element('p',found.length?'AIの回答ではなく、登録された本文をそのまま表示しています。':'根拠となる教材が見つかりませんでした。推測による回答は作成しません。'+(unsafe?'医療・安全に関する判断は、このデモでは扱えません。':'')));for(const {d} of found){const section=element('div',undefined,'source');section.append(element('b',d.title),element('p',d.text),element('small',`参照：${d.title} / 教材版 ${data.version}`));box.append(section)}if(!found.length){const save=element('button','未回答ノートに残す');save.onclick=()=>{if(!data.pending.some(p=>p.q===q))data.pending.push({q,version:data.version,date:new Date().toLocaleDateString('ja-JP')});const stored=persist();$('count').textContent=data.pending.length;save.disabled=true;save.textContent=stored?'このブラウザに保存しました':'一時保存しました（画面を閉じると消えます）'};box.append(save)}}
$('questionForm').onsubmit=e=>{e.preventDefault();search($('question').value)};for(const b of document.querySelectorAll('[data-q]'))b.onclick=()=>{$('question').value=b.dataset.q;search(b.dataset.q)};
function renderPending(){const list=$('pendingList');list.replaceChildren();if(!data.pending.length)list.append(element('p','未回答ノートは空です。'));data.pending.forEach((p,i)=>{const row=element('div',undefined,'pendingItem');row.append(element('strong',p.q),element('p',`${p.date} / 教材版 ${p.version} で未回答`));const btn=element('button','確認済みにする');btn.onclick=()=>{data.pending.splice(i,1);persist();$('count').textContent=data.pending.length;renderPending()};row.append(btn);list.append(row)});$('export').disabled=!data.pending.length}
$('export').onclick=()=>{const blob=new Blob(['提案用デモ・未回答ノート\n実送信なし\n\n'+data.pending.map(p=>`${p.date} / 版${p.version}\n${p.q}`).join('\n\n')],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='komorebi-unanswered.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
refresh();renderPending();tabs('ask');
