const $=s=>document.querySelector(s), money=n=>'¥'+n.toLocaleString('ja-JP'), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=()=>({orders:[{id:'M-0919-001',store:'こもれび店',qty:2,date:'2026-09-25',status:'preparing',unit:12000,tax:0.08,mail:'未接続',shipped:''},{id:'M-0918-002',store:'みなも店',qty:3,date:'2026-09-18',status:'shipped',unit:12000,tax:0.08,mail:'未接続',shipped:'2026-09-18'},{id:'M-0908-003',store:'ひだまり店',qty:1,date:'2026-09-10',status:'shipped',unit:12000,tax:0.08,mail:'未接続',shipped:'2026-09-10'},{id:'M-0831-004',store:'こもれび店',qty:2,date:'2026-08-31',status:'shipped',unit:11500,tax:0.08,mail:'未接続',shipped:'2026-08-31'}],logs:[{at:'初期サンプル',text:'8月・9月の発送済み注文と、未発送注文を用意しています。'}],next:5});
let data=initial(), view='overview', pending=null, selectedMonth='2026-09', filter='all';
try{const saved=JSON.parse(localStorage.getItem('musubi-demo-v1'));if(saved&&Array.isArray(saved.orders)&&Array.isArray(saved.logs)&&Number.isInteger(saved.next))data=saved}catch{}
const save=()=>{try{localStorage.setItem('musubi-demo-v1',JSON.stringify(data))}catch{toast('保存できませんでした。この画面内での体験は続けられます。')}};
const log=text=>{data.logs.unshift({at:new Date().toLocaleString('ja-JP'),text});save()};
let timer;function toast(t){$('#toast').textContent=t;clearTimeout(timer);timer=setTimeout(()=>$('#toast').textContent='',4500)}
const total=o=>o.qty*o.unit+Math.floor(o.qty*o.unit*o.tax);
const included=()=>data.orders.filter(o=>o.status==='shipped'&&o.shipped.startsWith(selectedMonth));
function title(en,jp,desc){const parts=jp.split('、');return `<p class="eyebrow">${en}</p><h1>${parts.map((s,i)=>`<span style="display:inline-block">${s}${i<parts.length-1?'、':''}</span>`).join('')}</h1><p class="intro">${desc}</p>`}
function go(v){view=v;document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.view===v?'page':'false'));render()}
function ask(title,body,fn,label='確定する'){$('#dialogtitle').textContent=title;$('#dialogbody').innerHTML=body;$('#commit').textContent=label;pending=fn;$('#confirm').showModal()}
$('#back').onclick=()=>{$('#confirm').close();pending=null};$('#confirm').addEventListener('cancel',()=>pending=null);$('#commit').onclick=()=>{const fn=pending;pending=null;$('#confirm').close();if(fn)fn()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
function pause(){const on=document.body.classList.toggle('paused');$('#motion').textContent=on?'動きを再開する':'動きを止める';$('#motion').setAttribute('aria-pressed',String(on));const m=$('#mobilemotion');if(m){m.textContent=$('#motion').textContent;m.setAttribute('aria-pressed',String(on))}}
$('#motion').onclick=pause;$('#reset').onclick=()=>ask('サンプルを初期状態に戻しますか？','<p>このデモ内の操作内容が初期サンプルに戻ります。実際の業務データはありません。</p>',()=>{data=initial();save();render();toast('初期サンプルに戻しました')},'初期状態に戻す');
function render(){const open=data.orders.filter(o=>o.status==='preparing'), shipped=data.orders.filter(o=>o.status==='shipped'&&o.shipped.startsWith('2026-09'));
 if(view==='overview'){$('#screen').innerHTML=title('OVERVIEW / SEPTEMBER 2026','今日の業務を、ひと目で。','注文を確かめる。発送する。月末にまとめる。次の操作へ迷わず進めます。')+`<div class="stats"><div class="stat accent"><p>発送準備中</p><strong>${open.length}<small>件</small></strong><em>発送待ちの注文</em></div><div class="stat"><p>9月の発送済み</p><strong>${shipped.length}<small>件</small></strong><em>発送日で集計</em></div><div class="stat"><p>9月の請求対象・仮金額</p><strong>${money(shipped.reduce((s,o)=>s+total(o),0))}</strong><em>未発送分は含みません</em></div></div><div class="grid"><section class="panel"><h2>次に確認する注文</h2>${open.length?open.map(o=>`<div class="row"><div><p>${esc(o.store)} · ${o.qty}箱</p><small>${esc(o.id)} / 発送予定 ${o.date}</small></div><span class="badge warn">発送準備中</span></div>`).join(''):'<p class="empty">発送待ちはありません</p>'}<div class="actions"><button class="primary" data-go="shipping">発送一覧を開く →</button></div></section><section class="panel tint"><p class="eyebrow">ONE SOURCE OF TRUTH</p><h2>注文は残す。<br>連携は、あとから再試行。</h2><p class="note">本番設計では、WordPressへの注文保存とメール・Sheetsへの連携を分けます。外部サービスの不調で、注文自体を失わない構成です。</p><div class="process"><div>01 保存<small>注文の正本</small></div><div>02 発送<small>状態を更新</small></div><div>03 請求<small>発送月で集計</small></div></div></section></div><section class="panel"><h2>このデモで試せること</h2><p class="note">店舗から発注 → 内容確認 → ブラウザ保存 → 発送済みに変更 → 月次請求へ反映。未発送の取消、操作履歴、CSV出力も試せます。認証やメール到達は接続していません。</p><button class="secondary" data-go="order">店舗の発注画面を試す</button></section>`}
 if(view==='order'){$('#screen').innerHTML=title('STORE ORDER','いつものお米を、迷わず発注。','店舗専用リンクから開いた場面のデモです。店舗・配送先は入力不要の想定です。')+`<div class="grid"><form class="panel" id="orderform"><h2>こもれび店からの発注</h2><div class="fixeddata"><p>店舗：こもれび店（架空）</p><p>発送先：店舗マスターに登録済みの発送先（仮）</p><p>通知先：登録済み宛先 2件（実アドレスなし）</p></div><div class="field"><label for="product">商品</label><input id="product" readonly value="業務用米・仮商品 / 1箱24kg（3kg×8袋）"></div><div class="field"><label for="shipdate">発送希望日</label><select id="shipdate"><option value="2026-09-25">2026年9月25日（金）</option><option value="2026-09-30">2026年9月30日（水）</option><option value="2026-10-02">2026年10月2日（金）</option></select></div><div class="field"><label for="quantity">箱数（1〜20箱）</label><input id="quantity" type="number" min="1" max="20" step="1" value="1" required></div><div class="amount"><span>仮合計（税込）</span><strong id="quote">¥12,960</strong></div><p class="note">1箱 税別12,000円・税率8%は体験用の仮設定です。変更・取消期限は契約条件から本番で確定し、発送日ごとに表示します。</p><p id="ordererror" class="error" role="alert"></p><button class="primary" type="submit">発注内容を確認する →</button></form><section class="panel tint"><p class="eyebrow">BEFORE YOU ORDER</p><h2>宛先を何度も<br>入力しなくていい。</h2><p class="note">本番では専用トークンから店舗を判定します。このデモには認証機能がなく、固定の架空店舗を表示しています。</p><h3>保存と通知を分ける</h3><p class="note">保存完了後に通知を処理する構成です。現在は外部サービス未接続のため、メール送信やSheets反映は行いません。</p><h3>取消は管理者へ</h3><p class="note">本番ではメール等の取消依頼を確認して管理者が処理します。店舗側に削除ボタンは設けません。</p></section></div>`;$('#quantity').oninput=()=>{const q=Number($('#quantity').value);$('#quote').textContent=Number.isInteger(q)&&q>=1&&q<=20?money(q*12960):'—'};$('#orderform').onsubmit=e=>{e.preventDefault();const qty=Number($('#quantity').value),date=$('#shipdate').value;if(!Number.isInteger(qty)||qty<1||qty>20){$('#ordererror').textContent='箱数は1〜20の整数で入力してください。';return}ask('この内容でデモ登録しますか？',`<p>こもれび店 · 業務用米</p><p>${qty}箱 / 発送希望 ${date}<br>仮合計 ${money(qty*12960)}（税込）</p><p class="note">このブラウザ内へ保存します。実発注・メール送信はありません。</p>`,()=>{const id='M-DEMO-'+String(data.next++).padStart(3,'0');data.orders.push({id,store:'こもれび店',qty,date,status:'preparing',unit:12000,tax:.08,mail:'未接続',shipped:''});log(id+' 注文をデモ登録');go('shipping');toast('デモ登録しました。メール・Sheetsは未接続です。')},'この内容をデモ登録')};}
 if(view==='shipping'){$('#screen').innerHTML=title('SHIPPING DESK','発送の状態を、確かに。','発送準備中／発送済みの2状態。取り消した注文は一覧と請求対象から除外します。')+`<section class="panel"><div class="controls"><div class="field"><label for="filter">表示する状態</label><select id="filter"><option value="all">すべて</option><option value="preparing">発送準備中</option><option value="shipped">発送済み</option></select></div><button class="secondary" id="export">一覧をCSVで出力</button></div><div class="tablewrap"><table><thead><tr><th>注文 / 店舗</th><th>発送予定</th><th>数量</th><th>状態 / 発送日</th><th>通知</th><th>操作</th></tr></thead><tbody>${data.orders.filter(o=>filter==='all'||o.status===filter).map(o=>`<tr><td>${esc(o.store)}<small>${esc(o.id)}</small></td><td>${o.date}</td><td>${o.qty}箱</td><td><span class="badge ${o.status==='preparing'?'warn':''}">${o.status==='preparing'?'発送準備中':'発送済み'}</span><small>${o.shipped||'—'}</small></td><td>未接続<small>到達・開封の実績なし</small></td><td>${o.status==='preparing'?`<button class="smallbutton" data-ship="${o.id}">発送済みにする</button><button class="smallbutton danger" data-cancel="${o.id}">取消</button>`:'<span class="note">訂正は個別確認</span>'}</td></tr>`).join('')}</tbody></table></div><p class="note" style="margin-top:18px">発送済みは通常の取消対象にしません。CSVは架空データの出力です。通知の「未接続」は、送信成功を意味しません。</p></section>`;$('#filter').value=filter;$('#filter').onchange=()=>{filter=$('#filter').value;render()};$('#export').onclick=()=>{downloadCSV('musubi-orders-demo.csv',[['注文番号','店舗','数量','発送予定','状態','発送日'],...data.orders.map(o=>[o.id,o.store,o.qty,o.date,o.status==='shipped'?'発送済み':'発送準備中',o.shipped])]);toast('架空の注文一覧CSVを出力しました')};document.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>{const o=data.orders.find(o=>o.id===b.dataset.ship);ask('発送日を確認してください',`<p>${esc(o.store)} / ${o.qty}箱</p><label for="actualdate">実際の発送日（デモ入力）</label><input id="actualdate" type="date" value="${o.date}"><p class="note">この日付を基準に月次請求へ集計します。</p>`,()=>{const d=$('#actualdate').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(d)){toast('発送日が未入力です。もう一度操作してください');return}o.status='shipped';o.shipped=d;log(o.id+' 発送済みへ変更 / '+d);render();toast('発送済みへ更新し、発送月の請求対象に反映しました')},'発送済みにする')});document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{const o=data.orders.find(o=>o.id===b.dataset.cancel);ask('未発送の注文を取り消しますか？',`<p>${esc(o.id)} / ${esc(o.store)} / ${o.qty}箱</p><p>管理者が取消依頼を確認した場面のデモです。注文の詳細を削除し、発送・請求の対象から除外します。</p><p class="note">最小限の注文番号・操作日時だけを履歴に残します。初期サンプルへ戻すと体験をやり直せます。</p>`,()=>{data.orders=data.orders.filter(x=>x.id!==o.id);log(o.id+' 取消・注文詳細をデモ内から削除');render();toast('注文を取り消し、一覧と請求対象から除外しました')},'取消を確定する')})}
 if(view==='billing'){const rows=included(),sub=rows.reduce((s,o)=>s+o.unit*o.qty,0),tax=rows.reduce((s,o)=>s+Math.floor(o.unit*o.qty*o.tax),0);$('#screen').innerHTML=title('MONTHLY BILLING','発送した分だけ、月末に。','発注日ではなく発送日で集計します。未発送・取消済みの注文は含まれません。')+`<section class="panel"><div class="controls"><div class="field"><label for="month">対象月</label><select id="month"><option value="2026-08">2026年8月</option><option value="2026-09">2026年9月</option><option value="2026-10">2026年10月</option></select></div><button class="secondary" id="csvbill">明細CSVを出力</button><button class="primary" id="print">印刷プレビュー</button></div><div class="invoice"><p class="eyebrow">FICTIONAL INVOICE / PREVIEW</p><h3>請求書プレビュー</h3><p>むすび食堂 本部（架空） 御中<br><span class="note">${selectedMonth} 発送分 · ${rows.length}件 / 全店舗を一括集計</span></p><p class="total">${money(sub+tax)} <span class="note">税込・仮金額</span></p><div class="tablewrap"><table><thead><tr><th>店舗 / 注文</th><th>発送日</th><th>箱数</th><th>税別単価</th><th>税別金額</th></tr></thead><tbody>${rows.map(o=>`<tr><td>${esc(o.store)}<small>${esc(o.id)}</small></td><td>${o.shipped}</td><td>${o.qty}</td><td>${money(o.unit)}</td><td>${money(o.qty*o.unit)}</td></tr>`).join('')}</tbody></table></div>${rows.length?'':'<p class="empty">この月に発送済みの注文はありません</p>'}<div class="amount"><span>小計 ${money(sub)}<br>消費税相当 ${money(tax)}（仮税率8%）</span><strong>${money(sub+tax)}</strong></div><p class="note">各注文に保存した単価・税率を使用。端数は注文単位で切捨てるデモ設定です。本番は合意した丸めルールに統一します。<br>振込先：［口座情報は本人が別途案内］<br>正式な請求書ではありません。PDF生成・メール送付・入金管理は未接続です。</p></div></section>`;$('#month').value=selectedMonth;$('#month').onchange=()=>{selectedMonth=$('#month').value;render()};$('#print').onclick=()=>window.print();$('#csvbill').onclick=()=>{downloadCSV('musubi-billing-'+selectedMonth+'-demo.csv',[['注文番号','店舗','発送日','箱数','税別単価','税別金額'],...rows.map(o=>[o.id,o.store,o.shipped,o.qty,o.unit,o.qty*o.unit])]);toast('請求対象の架空明細CSVを出力しました')};}
 if(view==='log'){$('#screen').innerHTML=title('ACTIVITY LOG','いつ、何をしたか。','このブラウザで行った操作履歴です。認証付きの本番監査ログではありません。')+`<section class="panel">${data.logs.map(l=>`<div class="ledger"><time>${esc(l.at)}</time><p>${esc(l.text)}</p></div>`).join('')}<div class="actions"><button class="secondary" id="resetmobile">サンプルを初期状態に戻す</button></div></section>`;$('#resetmobile').onclick=()=>$('#reset').click()}
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#screen').insertAdjacentHTML('beforeend',`<button class="secondary mobilemotion" id="mobilemotion" aria-pressed="${document.body.classList.contains('paused')}">${document.body.classList.contains('paused')?'動きを再開する':'動きを止める'}</button>`);$('#mobilemotion').onclick=pause;
}
function downloadCSV(name,rows){const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
render();
