const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
let paused=localStorage.getItem('wakan-motion')==='off';const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function motion(){document.documentElement.classList.toggle('paused',paused||reduced.matches);$('#motion').textContent=paused?'動きを再開する':'動きを止める';$('#motion').setAttribute('aria-pressed',paused)}motion();$('#motion').onclick=()=>{paused=!paused;localStorage.setItem('wakan-motion',paused?'off':'on');motion()};reduced.addEventListener('change',motion);
document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');observer.unobserve(e.target)}}),{threshold:.08});all('.reveal').forEach(e=>observer.observe(e));
$('#menu').onclick=()=>{const open=$('nav').classList.toggle('open');$('#menu').setAttribute('aria-expanded',open)};
const slides=[['経営を語り、<br>人生をひらく。','一人で考えていたことを、<br>信頼できる仲間と、これからの一歩へ。','lounge.webp'],['新しい視点を、<br>対話のなかに。','立場の違いを、学びのきっかけに。<br>同じテーブルから、可能性が広がります。','dialogue.webp'],['立ち止まる時間が、<br>明日をつくる。','経営と暮らしを、少し広い視野で。<br>大切にしたいことから、歩きはじめる。','lounge.webp']];all('[data-slide]').forEach(b=>b.onclick=()=>{all('[data-slide]').forEach(x=>x.setAttribute('aria-pressed',x===b));const s=slides[+b.dataset.slide];$('#hero-title').innerHTML=s[0];$('#hero-desc').innerHTML=s[1];$('#hero-img').src=s[2]});
const perspectives=['経済：これからの事業と暮らしを、長い時間軸で考える。','健康：毎日の選択から、心と体を大切にする。','教養：知らない世界に触れ、問いを深める。','社会：仕事や地域を通して、周囲との関係を考える。','精神：自分の価値観に向き合い、判断の軸を育てる。','家庭：身近な人と、これからの時間を話し合う。'];all('[data-life]').forEach(b=>b.onclick=()=>{all('[data-life]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#life-text').textContent=perspectives[+b.dataset.life]});
all('[data-filter]').forEach(b=>b.onclick=()=>{all('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));let n=0;all('[data-category]').forEach(c=>{c.hidden=b.dataset.filter!=='すべて'&&c.dataset.category!==b.dataset.filter;if(!c.hidden){n++;c.classList.add('seen')}});$('#count').textContent=n+'件のサンプル記事'});
const articles=[['視察','現場から、経営の問いを持ち帰る。','工場の動線をたどり、日々の小さな工夫に目を向ける。対話で気づきを整理する視察プログラムのイメージです。'],['学び','これからの時間を、考える午後。','仕事に加え、健康や家族との時間まで。六つの視点で大切にしたいことを言葉にする勉強会のイメージです。'],['交流','立場を離れて、話せる食卓。','一人ずつの問いを持ち寄る少人数の対話会。答えを急がず、異なる視点に出会う時間のイメージです。']];if($('#article-title')){const i=Number(new URLSearchParams(location.search).get('id'));const a=articles[i]||articles[0];$('#article-title').textContent=a[1];$('#article-category').textContent=a[0]+' / SAMPLE';$('#article-body').textContent=a[2];if(i===2)$('.article-img').src='dialogue.webp'}
if($('form#consult')){const t=new URLSearchParams(location.search).get('type');all('[name=type]').forEach(x=>x.checked=x.value===t);$('#consult').onsubmit=e=>{e.preventDefault();$('#chosen-type').textContent=$('[name=type]:checked').value;$('#chosen-interest').textContent=$('#interest').value;$('#consult').hidden=true;$('#confirmation').hidden=false;$('#confirmation').focus();$('#confirmation').scrollIntoView({block:'start'})};$('#edit').onclick=()=>{$('#confirmation').hidden=true;$('#consult').hidden=false;$('#consult').scrollIntoView({block:'start'});$('[name=type]:checked').focus()}};
