const $=s=>document.querySelector(s);let pages,categories,history,inquiries,products,view='pages',selected=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function initial(){pages=[{id:1,title:'サービスのご案内',category:'サービス',body:'<h2>暮らしを支えるサービス</h2>\n<p>架空の紹介文です。</p>',state:'下書き'},{id:2,title:'展示会のお知らせ',category:'ニュース',body:'<p>架空の展示会のお知らせ。</p>',state:'確認待ち'},{id:3,title:'会社について',category:'企業情報',body:'<p>凪企画は架空の企業です。</p>',state:'公開予定'}];categories=['サービス','ニュース','企業情報'];history=[];inquiries=[{id:1,subject:'製品についての仮のお問い合わせ',state:'未対応',notes:[]}];products=[];selected=null;render()}
function notify(t){$('#status').textContent=t}function log(t){history.unshift(new Date().toLocaleTimeString('ja-JP')+' '+t)}function canEdit(){return $('#role').value!=='閲覧者'}function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#heading').textContent=({pages:'コンテンツ',categories:'カテゴリー',inquiries:'問い合わせ',products:'商品連携',history:'操作履歴'})[view];$('#count').textContent=pages.length;let html='';
if(view==='pages'){html='<div class="tools"><input id="search" aria-label="ページを検索" placeholder="ページ名を検索"><button id="new" '+(!canEdit()?'disabled':'')+'>新しい下書き</button></div><div class="cards" id="list"></div><div id="edit"></div>'}
if(view==='categories'){html='<div class="editor"><h2>カテゴリーと更新の整理</h2><ul>'+categories.map(c=>'<li>'+esc(c)+' / '+pages.filter(p=>p.category===c).length+'ページ</li>').join('')+'</ul><label>新しいカテゴリー<input id="cat" maxlength="30"></label><button id="addcat" '+($('#role').value!=='管理者'?'disabled':'')+'>カテゴリーを追加</button><p class="muted">追加できるのは管理者の体験モードです。</p></div>'}
if(view==='inquiries'){let q=inquiries[0];html='<div class="editor"><span class="badge">'+q.state+'</span><h2>'+q.subject+'</h2><p>送信者は架空です。実際のメール受信・返信はありません。</p><label>内部メモ<textarea id="note" placeholder="仮の対応メモ"></textarea></label><button id="saveNote" '+(!canEdit()?'disabled':'')+'>メモを保存</button> <button id="resolve" '+(!canEdit()?'disabled':'')+'>対応済みにする</button><ul>'+q.notes.map(n=>'<li>'+esc(n)+'</li>').join('')+'</ul></div>'}
if(view==='products'){html='<div class="editor"><h2>取り込む前に、内容を確認。</h2><p>架空の商品データ2件を確認して、この画面内の一覧へ取り込みます。外部APIには接続しません。</p><button id="stage">仮データを読み込む</button><div id="staged"></div><h3>取り込み済み '+products.length+'件</h3><ul>'+products.map(p=>'<li>'+p+'</li>').join('')+'</ul><p class="muted">同じ商品コードは重複登録しない体験です。価格情報は使用しません。</p></div>'}
if(view==='history')html='<div class="editor"><h2>この画面の操作履歴</h2><ul>'+history.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul><p class="muted">'+(history.length?'ブラウザーの再読み込みで消えます。':'まだ操作がありません。')+'</p></div>';
$('#workspace').innerHTML=html;
if(view==='pages'){list();$('#search').oninput=list;$('#new').onclick=()=>{if(!canEdit())return;let p={id:Date.now(),title:'新しいページ',category:categories[0],body:'<p>仮の本文</p>',state:'下書き'};pages.push(p);log('下書きを追加');selected=p.id;render()};if(selected)edit(selected)}
if(view==='categories')$('#addcat').onclick=()=>{let c=$('#cat').value.trim();if($('#role').value!=='管理者')return;if(!c||categories.includes(c)){notify('カテゴリー名が空欄、または登録済みです。');return}categories.push(c);log('カテゴリーを追加');notify('カテゴリーを追加しました。');render()};
if(view==='inquiries'){$('#saveNote').onclick=()=>{if(!canEdit())return;let n=$('#note').value.trim();if(!n){notify('メモを入力してください。');return}inquiries[0].notes.push(n);log('問い合わせにメモを追加');notify('画面内にメモを保存しました。');render()};$('#resolve').onclick=()=>{if(!canEdit())return;inquiries[0].state='対応済み';log('問い合わせを対応済みに変更');notify('対応済みにしました。返信は送信されません。');render()}}
if(view==='products')$('#stage').onclick=()=>{$('#staged').innerHTML='<p>NG-001 仮の照明 / NG-002 仮の収納</p><button id="import" '+(!canEdit()?'disabled':'')+'>2件を確認して取り込む</button>';$('#import').onclick=()=>{if(!canEdit())return;products=['NG-001 仮の照明','NG-002 仮の収納'];log('商品2件を取り込み（重複は更新）');notify('仮データ2件を取り込みました。');render()}};
}
function list(){let term=$('#search').value;$('#list').innerHTML=pages.filter(p=>p.title.includes(term)).map(p=>'<article class="card"><div><span class="badge">'+esc(p.category)+' / '+p.state+'</span><h2>'+esc(p.title)+'</h2><span class="muted">ページ #'+p.id+'</span></div><button data-edit="'+p.id+'">内容を開く</button></article>').join('')||'<p>該当するページはありません。</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(Number(b.dataset.edit)))}
function edit(id){selected=id;let p=pages.find(p=>p.id===id),disabled=!canEdit()?'disabled':'';$('#edit').innerHTML='<div class="editor"><h2>ページの編集</h2><label>ページ名<input id="title" maxlength="80" value="'+esc(p.title)+'" '+disabled+'></label><label>カテゴリー<select id="category" '+disabled+'>'+categories.map(c=>'<option '+(p.category===c?'selected':'')+'>'+esc(c)+'</option>').join('')+'</select></label><label>HTML本文<textarea id="body" '+disabled+'>'+esc(p.body)+'</textarea></label><p class="muted">安全のため、このデモはHTMLを実行せず文字列として表示します。本番のHTML許可範囲・画像管理は要件定義で確定します。</p><div class="tools"><button id="preview">内容を確認</button><button id="save" '+disabled+'>下書き保存</button><button id="request" '+disabled+'>確認待ちにする</button><button id="publish" '+($('#role').value!=='管理者'?'disabled':'')+'>公開予定にする</button></div><div class="preview" id="previewText">'+esc(p.body)+'</div></div>';
$('#preview').onclick=()=>{$('#previewText').textContent=$('#body').value;notify('本文を文字列として確認しました。')};function save(state){if(!canEdit())return;if(!$('#title').value.trim()){notify('ページ名を入力してください。');return}p.title=$('#title').value.trim();p.category=$('#category').value;p.body=$('#body').value;p.state=state;log('ページ「'+p.title+'」を'+state+'に変更');notify(state+'にしました。実際のサイト公開は行いません。');render()}
$('#save').onclick=()=>save('下書き');$('#request').onclick=()=>save('確認待ち');$('#publish').onclick=()=>{if($('#role').value==='管理者')save('公開予定')};}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;selected=null;render()});$('#role').onchange=()=>{notify('権限体験を切り替えました。本番認証ではありません。');render()};$('#reset').onclick=()=>{initial();notify('仮データを初期化しました。')};initial();
