(() => {
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');let observer,frame=0;
 const progress=document.createElement('div');progress.className='reading-progress';progress.setAttribute('aria-hidden','true');document.body.append(progress);
 document.querySelectorAll('h1,h2').forEach(h=>{h.innerHTML=h.innerHTML.split(/<br\s*\/?\s*>/i).map((line,i)=>`<span class="line-mask"><span class="line-inner" style="--line:${i}">${line}</span></span>`).join('');});
 // Text motion preserves the full heading as its accessible name.
 document.querySelectorAll('h1,h2,.program-list h3,.method h3,.steps h3').forEach(heading=>{
  heading.setAttribute('aria-label',heading.textContent);heading.classList.add('type-heading');let index=0;
  function split(parent){[...parent.childNodes].forEach(node=>{if(node.nodeType===3){const frag=document.createDocumentFragment();const tokens=node.textContent.match(/[^\s][、。！？）」』】]?|\s+/gu)||[];tokens.forEach(token=>{if(/^\s+$/.test(token)){frag.append(document.createTextNode(token));return;}const span=document.createElement('span');span.className='type-char';span.textContent=token;span.setAttribute('aria-hidden','true');span.style.setProperty('--char',Math.min(index++,22));frag.append(span);});node.replaceWith(frag);}else if(node.nodeType===1)split(node);});}split(heading);
 });
 const targets=[...document.querySelectorAll('.intro>div,.approach-grid>div,.section-head>div,.section-head>p,.program-list>a,.closing .wrap,.detail-section,.method li,.steps li')];
 function setup(){observer?.disconnect();document.body.classList.toggle('motion-on',!reduced.matches);targets.forEach(el=>el.classList.remove('is-pending'));if(reduced.matches||!('IntersectionObserver' in window))return;observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('is-pending');e.target.classList.add('is-visible');observer.unobserve(e.target);}})},{threshold:.04,rootMargin:'0px 0px -30px 0px'});targets.forEach(el=>{el.classList.add('motion-target');if(el.getBoundingClientRect().top>innerHeight*.9){el.classList.add('is-pending');observer.observe(el);}else el.classList.add('is-visible');});}
 function tick(){frame=0;if(reduced.matches)return;const distance=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${distance>0?Math.min(1,Math.max(0,scrollY/distance)):0})`;const word=document.querySelector('.hero-word');if(word)word.style.setProperty('--word-x',`${Math.min(40,scrollY*.065)}px`);const photo=document.querySelector('.approach-image img');if(photo){const r=photo.parentElement.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight){const offset=(r.top+r.height/2-innerHeight/2)*-.03;photo.style.transform=`translateY(${Math.max(-14,Math.min(14,offset))}px) scale(1.08)`;}}}
 function schedule(){if(!frame)frame=requestAnimationFrame(tick);}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);reduced.addEventListener('change',()=>{setup();if(reduced.matches){progress.style.transform='scaleX(0)';const photo=document.querySelector('.approach-image img');if(photo)photo.style.transform='none';}else schedule();});setup();schedule();
 document.querySelectorAll('details').forEach(detail=>detail.addEventListener('toggle',()=>{if(detail.open&&!reduced.matches){detail.querySelector('div,p')?.animate([{opacity:0,transform:'translateY(-6px)'},{opacity:1,transform:'translateY(0)'}],{duration:300,easing:'ease-out'});}}));
 const sections=document.querySelectorAll('.detail-section');if(sections.length&&'IntersectionObserver' in window){const active=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)document.querySelectorAll('aside a').forEach(link=>{const yes=link.hash==='#'+entry.target.id;link.classList.toggle('active',yes);if(yes)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});},{rootMargin:'-15% 0px -65% 0px'});sections.forEach(s=>active.observe(s));}
})();
