(()=>{'use strict';const $=id=>document.getElementById(id),deck=JSON.parse($('slide-data').textContent),slides=deck.slides;let index=0,step=0,progress=1,from={},to={},state={},raf=0,start=0,paused=false;const duration=1800,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function mix(a,b,t){const o={...b};for(const k in b)if(typeof b[k]==='number')o[k]=(a[k]??b[k])+(b[k]-(a[k]??b[k]))*t;return o;}
function paint(){state=mix(from,to,progress);Astro.render($('scene'),slides[index],state,step);$('motion').value=Math.round(progress*1000);$('pause').textContent=paused?'再開':'一時停止';}
function tick(now){progress=Math.min(1,(now-start)/duration);paint();if(progress<1&&!paused)raf=requestAnimationFrame(tick);}
function animate(){cancelAnimationFrame(raf);paused=false;if(reduced){finish();return;}start=performance.now()-progress*duration;raf=requestAnimationFrame(tick);}
function finish(){cancelAnimationFrame(raf);progress=1;paused=false;paint();}
function show(i,n=0,motion=false){cancelAnimationFrame(raf);index=Math.max(0,Math.min(slides.length-1,i));const s=slides[index];step=Math.max(0,Math.min(s.notes.length,n));$('stage').className=s.kind||'';$('visual').style.backgroundImage=s.coverImage?`url("${s.coverImage}")`:'';$('title').textContent=s.title;$('kicker').textContent='中3 理科　／　'+deck.title;$('caption').textContent=s.caption||'';
$('notes-grid').replaceChildren(...s.notes.map((text,j)=>{const e=document.createElement('div');let red=text.startsWith('!');e.className='sticky'+(red?' answer':'')+(j<step?' shown':'')+(motion&&j===step-1?' entering':'');const t=document.createElement('span');t.className='stamp';t.textContent=red?text.slice(1):text;e.append(t);return e;}));
$('teacher-text').textContent=s.teacher+'\n\n参照：\n'+deck.sources.join('\n');$('select').value=index;$('counter').textContent=`${index+1} / ${slides.length}　段階 ${step}/${s.notes.length}`;
from={...s.states[Math.max(0,step-1)]};to={...s.states[step]};progress=motion&&JSON.stringify(from)!==JSON.stringify(to)?0:1;paused=false;history.replaceState(null,'','#'+(index+1));paint();if(progress<1)animate();}
function next(){if(step<slides[index].notes.length)show(index,step+1,true);else if(index<slides.length-1)show(index+1);}
function previous(){if(step>0)show(index,step-1);else if(index>0)show(index-1,slides[index-1].notes.length);}
function scale(){document.documentElement.style.setProperty('--scale',Math.min(innerWidth/1920,(innerHeight-46)/1080));$('stage').style.top=(innerHeight-46)/2+'px';}
slides.forEach((s,i)=>{const e=document.createElement('option');e.value=i;e.textContent=`${i+1}　${s.title}`;$('select').append(e);});
document.addEventListener('click',e=>{if(!e.target.closest('[data-no-tap],button,input,select,a'))next();});document.addEventListener('contextmenu',e=>{if(e.target.closest('[data-no-tap]'))return;e.preventDefault();previous();});document.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,#teacher'))return;if(['ArrowRight','ArrowLeft',' ','PageDown','PageUp'].includes(e.key)){e.preventDefault();(['ArrowLeft','PageUp'].includes(e.key)?previous:next)();}});
$('next').onclick=next;$('prev').onclick=previous;$('select').onchange=e=>show(Number(e.target.value));$('teacher-toggle').onclick=()=>{$('teacher').hidden=!$('teacher').hidden;};$('teacher-close').onclick=()=>{$('teacher').hidden=true;};$('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('pause').onclick=()=>{if(progress>=1)return;paused=!paused;if(paused){cancelAnimationFrame(raf);paint();}else animate();};$('replay').onclick=()=>{progress=0;animate();};$('motion').oninput=e=>{cancelAnimationFrame(raf);paused=true;progress=Number(e.target.value)/1000;paint();};
window.SeedAstro={show,next,previous,finishAnimation:finish,get index(){return index;},get step(){return step;},get state(){return {...state};},get progress(){return progress;},slides};addEventListener('resize',scale);scale();show((Number(location.hash.slice(1))||1)-1);document.fonts.ready.then(paint);Astro.ready.then(paint);
})();
