'use strict';
const products=[{id:'YN-001',brand:'NOMA',name:'レザートート / キャメル',category:'バッグ',price:48000,condition:'A',size:'W30 × H24 × D12 cm',model:'NT-26',image:'bag',note:'角にわずかな擦れを想定した架空例。実物の検品結果ではありません。'},{id:'YN-002',brand:'SAE',name:'ステンレスウォッチ',category:'時計',price:76000,condition:'B',size:'ケース径 34 mm',model:'SW-04',image:'watch',note:'ベルトに小傷を想定した架空例。動作・精度の保証を示すものではありません。'},{id:'YN-003',brand:'NOMA',name:'二つ折りウォレット',category:'財布',price:18000,condition:'B',size:'W11 × H9 cm',model:'NW-12',image:'wallet',note:'折り目に使用感を想定した架空例。仕様・写真は仮のものです。'},{id:'YN-004',brand:'SAE',name:'シルクスカーフ / アイボリー',category:'スカーフ',price:24000,condition:'A',size:'70 × 70 cm',model:'SS-70',image:'scarf',note:'軽い保管皺を想定した架空例。素材表記も仮設定です。'}];
const $=id=>document.getElementById(id),money=n=>'¥'+n.toLocaleString('ja-JP');let stock=Object.fromEntries(products.map(p=>[p.id,true])),bag=[],orders=[],counter=0,events=[];
function log(text){events.unshift(new Date().toLocaleTimeString('ja-JP')+' '+text);$('events').replaceChildren(...events.slice(0,12).map(t=>{let li=document.createElement('li');li.textContent=t;return li}));}
function render(){let found=products.filter(p=>[p.name,p.id,p.model].join(' ').toLowerCase().includes($('query').value.trim().toLowerCase())&&(!$('brand').value||p.brand===$('brand').value)&&(!$('category').value||p.category===$('category').value)&&(!$('price').value||p.price<=Number($('price').value))&&(!$('condition').value||p.condition===$('condition').value));if($('sort').value==='low')found.sort((a,b)=>a.price-b.price);if($('sort').value==='high')found.sort((a,b)=>b.price-a.price);$('resultCount').textContent=found.length+'件の架空商品';$('products').innerHTML=found.map(p=>`<article class="product"><button data-detail="${p.id}" aria-label="${p.name}の商品詳細"><div class="image"><img src="assets/${p.image}.jpg" alt="AI生成の架空${p.category}" loading="lazy"><span class="badge">${stock[p.id]?'状態 '+p.condition:'SOLD OUT'}</span></div><p class="brand">${p.brand} / 架空ブランド</p><h3>${p.name}</h3><p class="price">${money(p.price)} <small>税込・仮価格</small></p><small>${p.id} · 詳細を見る ↗</small></button></article>`).join('')||'<p>条件に合う商品はありません。条件をクリアして再度お試しください。</p>';$('products').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));$('cartCount').textContent=bag.length;}
function detail(id){const p=products.find(p=>p.id===id);$('detailBody').innerHTML=`<div class="detailGrid"><div><img id="detailImage" src="assets/${p.image}.jpg" alt="AI生成の架空${p.category}"><div class="galleryButtons"><button id="single">商品写真</button><button id="scene">コレクション写真</button></div><p class="small">2枚ともAI生成の仮画像。実物の状態証拠ではありません。</p></div><div><p class="eyebrow">${p.brand} / FICTIONAL BRAND</p><h2>${p.name}</h2><p>${money(p.price)}（税込・仮価格）</p><dl><dt>商品コード</dt><dd>${p.id}</dd><dt>型番</dt><dd>${p.model}</dd><dt>状態</dt><dd>${p.condition} / 仮設定</dd><dt>サイズ</dt><dd>${p.size} / 仮設定</dd><dt>在庫</dt><dd>${stock[id]?'1点（デモ）':'売切れ（デモ）'}</dd><dt>付属品</dt><dd>仮の保管袋</dd></dl><p>${p.note}</p><button id="add" ${!stock[id]||bag.includes(id)?'disabled':''}>${bag.includes(id)?'バッグに追加済み':'バッグに入れる（デモ）'}</button><p class="small">この操作だけでは在庫を確保しません。</p></div></div>`;$('single').onclick=()=>{$('detailImage').src='assets/'+p.image+'.jpg'};$('scene').onclick=()=>{$('detailImage').src='assets/hero.jpg'};$('add').onclick=()=>{if(!stock[id]||bag.includes(id))return;bag.push(id);log(id+' バッグに追加（在庫未確保）');render();$('detail').close();openCart()};$('detail').showModal();}
function openCart(){renderCart();$('cart').showModal()}
function renderCart(){const rows=bag.map(id=>products.find(p=>p.id===id));$('cartBody').innerHTML=rows.map(p=>`<div class="cartRow"><img src="assets/${p.image}.jpg" alt="架空${p.category}"><div><h3>${p.name}</h3><p>${money(p.price)}</p><small>${stock[p.id]?'在庫確認前':'現在売切れ（デモ）'}</small></div><button data-remove="${p.id}" aria-label="${p.name}をバッグから削除">削除</button></div>`).join('')||'<p>バッグは空です。商品詳細から追加できます。</p>';if(rows.length)$('cartBody').insertAdjacentHTML('beforeend',`<p>商品合計 ${money(rows.reduce((s,p)=>s+p.price,0))}（税込・仮価格）</p>`);$('cartBody').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{bag=bag.filter(id=>id!==b.dataset.remove);render();renderCart()});$('checkout').disabled=!rows.length;$('cartStatus').textContent='';}
$('checkout').onclick=()=>{if(!bag.length)return;const unavailable=bag.filter(id=>!stock[id]);if(unavailable.length){$('cartStatus').textContent='在庫が変わったため仮注文を停止しました。売切れ商品を削除してください。';log('在庫競合を検知：仮注文を停止 '+unavailable.join(','));return;}const items=[...bag];items.forEach(id=>stock[id]=false);orders.unshift({id:'DEMO-'+String(++counter).padStart(3,'0'),items,status:'仮注文受付'});bag=[];render();renderCart();renderOrders();$('cartStatus').textContent='ブラウザ内に仮注文を記録しました。実注文・決済・通知は行っていません。';log(orders[0].id+' 仮注文記録。在庫をデモ上で確保');};
function renderOrders(){$('orders').innerHTML=orders.map(o=>`<div class="order"><strong>${o.id}</strong> / ${o.status}<p>${o.items.join(' / ')}</p>${o.status==='仮注文受付'?`<button data-ship="${o.id}">出荷済みを再現</button><button data-cancel="${o.id}" class="quiet">仮注文を取消</button>`:''}</div>`).join('')||'仮注文はまだありません。';$('orders').querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>{let o=orders.find(o=>o.id===b.dataset.ship);o.status='出荷済み（デモ）';renderOrders();log(o.id+' 出荷状態更新。実出荷なし')});$('orders').querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{let o=orders.find(o=>o.id===b.dataset.cancel);o.status='取消済み（デモ）';o.items.forEach(id=>stock[id]=true);renderOrders();render();log(o.id+' 取消・在庫を戻しました')});}
$('inventoryItem').innerHTML=products.map(p=>`<option value="${p.id}">${p.id} ${p.name}</option>`).join('');
function inventory(value){const id=$('inventoryItem').value;if(value&&orders.some(o=>o.status!=='取消済み（デモ）'&&o.items.includes(id))){$('syncStatus').textContent='仮注文がある商品は在庫を戻せません。先に仮注文を取り消してください。';return;}stock[id]=value;render();$('syncStatus').textContent=id+(value?' の在庫を戻しました。':' の売切れを反映しました。')+' 外部通信なし。';log($('syncStatus').textContent);}
$('sold').onclick=()=>inventory(false);$('restore').onclick=()=>inventory(true);$('reset').onclick=()=>{stock=Object.fromEntries(products.map(p=>[p.id,true]));bag=[];orders=[];counter=0;events=[];render();renderOrders();log('体験データ初期化');$('syncStatus').textContent='架空データ読み込み済み。外部同期なし。'};
$('filters').oninput=render;$('filters').onsubmit=e=>e.preventDefault();$('filters').onreset=()=>setTimeout(render,0);$('cartButton').onclick=openCart;document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('motion').onclick=()=>{const stopped=document.body.classList.toggle('still');$('motion').textContent=stopped?'動きを再開':'動きを止める';$('motion').setAttribute('aria-pressed',String(stopped))};render();
