'use strict';
const $ = (q, el = document) => el.querySelector(q);
const main = $('#main');
const STORE = 'madoi-easy-demo-v1';
const TODAY = '2026-09-15';
const clients = ['青葉商店（架空）', 'つばめ工房（架空）', 'こもれび運送（架空）'];
const initial = () => ({version:1, large:false, replies:{}, tasks:[
  {id:'t1',title:'入社の書類を確認する',client:clients[0],due:TODAY,owner:'担当A',done:false,description:'届いている入社書類に不足がないか確認します。手続きの提出は、いつもの業務ソフトで行います。',checks:['入社日と氏名を確認した','必要な書類がそろっているか確認した'],origin:null},
  {id:'t2',title:'更新書類の押印を確認する',client:clients[1],due:TODAY,owner:'担当B',done:false,description:'更新書類の押印欄を確認し、不足があれば担当者へ共有します。',checks:['押印が必要な箇所を確認した','不足している箇所の有無を確認した'],origin:null},
  {id:'t3',title:'面談の記録を整理する',client:clients[2],due:'2026-09-16',owner:'担当A',done:false,description:'面談メモを確認して、次に必要な対応を整理します。',checks:['面談の内容を確認した','次の対応と担当者を確認した'],origin:null}
],registered:[]});
let state = initial(), saveFailed = false, activeRequest = null, draft = null, returnTo = 'today', lastUndo = null, resultQuery = '';
try {
  const raw = localStorage.getItem(STORE);
  if (raw) { const s = JSON.parse(raw); if(s.version===1 && Array.isArray(s.tasks) && s.tasks.length<=50 && s.tasks.every(t=>typeof t.id==='string' && typeof t.title==='string' && clients.includes(t.client) && Array.isArray(t.checks) && typeof t.done==='boolean') && Array.isArray(s.registered) && s.registered.every(id=>['r1','r2','r3'].includes(id))){ state=s; } else {saveFailed=true;} }
} catch { saveFailed=true; }
const requests = [
 {id:'r3',channel:'公式LINE',time:'10:40',title:'公式LINEで、書類の相談が届きました',client:clients[1],task:'更新書類の受け取り方法を案内する',due:'',source:'更新の書類がそろいました。\n郵送と持参、どちらがよいでしょうか。',note:'書類の受け取り方法についての相談です。期限はメッセージにないため、確認待ちにしています。',reply:'書類のご準備ありがとうございます。\n受け取り方法を担当者に確認のうえ、改めてご案内いたします。'},
 {id:'r1',channel:'メール',time:'9:10',title:'入社書類が届いています',client:clients[0],task:'入社書類の不足を確認する',due:'2026-09-16',source:'お世話になっております。\n来月入社予定の方の書類をお送りします。\n足りないものがありましたら、確認して教えてください。\n\n青葉商店（架空）',note:'書類の受け取りを確認し、不足がないか確認する依頼です。'},
 {id:'r2',channel:'音声メモ',time:'10:25',title:'どの顧問先か、確認が必要です',client:'',task:'書類の受け取り状況を確認する',due:'',source:'「先ほどのお電話の件です。\n例の書類、届いているか確認をお願いします。」\n\n音声からの書き起こし例（架空）',note:'メモに顧問先の名前がありません。推測せず、確認した顧問先を選んでください。'}
];
const notes = [
 {id:'n1',title:'入社の書類を受け取るとき',keys:['入社','書類','必要','受け取','準備'],answer:'まず、入社日とご担当者を確認します。次に、事務所の「入社書類チェック表」と照合し、不足があれば確認待ちとして記録します。\n提出が必要な手続きや期限は、担当者に確認してください。',source:'入社書類の受け取り手順',updated:'2026年9月10日',text:'1. 顧問先、入社日、連絡担当者を確認する。\n2. 入社書類チェック表と届いた書類を照合する。\n3. 不足がある場合は「確認待ち」として担当者に共有する。\n4. 個人番号を含む資料はこの画面に取り込まず、事務所で指定された別の管理方法を使う。\n5. 手続きの種類と法定期限は担当者が確認する。'},
 {id:'n2',title:'顧問先が分からない依頼は？',keys:['顧問先','不明','分から','わから','電話','依頼'],answer:'分からないまま案件に登録せず、確認待ちにします。電話メモや担当者に確認し、顧問先が分かってから登録します。',source:'依頼の振り分けルール',updated:'2026年9月12日',text:'1. 顧問先を特定できない依頼は確認待ちにする。\n2. 送信元と内容だけで推測して確定しない。\n3. 元のメモと担当者への確認により顧問先を確定する。\n4. 確認した顧問先と担当者を選び、案件へ登録する。'},
 {id:'n3',title:'仕事を間違えて完了にしたら？',keys:['完了','取り消','取消','間違','戻'],answer:'「今日やること」の下にある「完了した仕事」を開きます。該当する仕事の「未完了に戻す」を押すと、仕事の一覧に戻ります。',source:'仕事画面の操作手順',updated:'2026年9月14日',text:'1. 「今日やること」を開く。\n2. 「完了した仕事」を開く。\n3. 対象を確認して「未完了に戻す」を押す。\n4. 一覧に戻ったことを確認する。\n\n完了操作は記録上の状態変更です。外部への手続きや送信は実行されません。'}
];
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));saveFailed=false;}catch{saveFailed=true;}storageNotice();}
function storageNotice(){const el=$('#storage-warning');el.hidden=!saveFailed;el.textContent='このブラウザでは保存できませんでした。画面を閉じると操作が元に戻る場合があります。';}
function applySize(){document.documentElement.classList.toggle('large-text',state.large);$('#font-toggle').setAttribute('aria-pressed',String(state.large));$('#font-toggle').lastElementChild.textContent=state.large?'文字を元に戻す':'文字を大きく';}
function remaining(){return requests.filter(r=>!state.registered.includes(r.id));}
function nav(view){document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#today-count').textContent=state.tasks.filter(t=>!t.done).length;$('#inbox-count').textContent=remaining().length;}
function focusMain(){main.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function go(view){if(location.hash!=='#'+view)history.pushState(null,'','#'+view);route();}
function dateLabel(d){if(!d)return '期限の確認待ち';if(d===TODAY)return '今日まで';if(d==='2026-09-16')return '明日まで';const [y,m,day]=d.split('-');return `${Number(m)}月${Number(day)}日まで`;}
function taskRows(tasks){return tasks.map(t=>`<article class="task-row ${t.done?'completed':t.due===TODAY?'urgent':''}"><div><div class="task-meta"><span class="pill ${t.done?'green':t.due===TODAY?'urgent':''}">${t.done?'✓ 完了':esc(dateLabel(t.due))}</span><span>${esc(t.client)}</span></div><h3>${esc(t.title)}</h3><p class="task-sub">担当：${esc(t.owner)}</p></div><button class="${t.done?'done-button':t.due===TODAY?'primary':'secondary'}" data-action="${t.done?'reopen':'task'}" data-id="${esc(t.id)}">${t.done?'未完了に戻す':'内容を確認'}${t.done?'':'　›'}</button></article>`).join('');}
function today(){nav('today');const open=state.tasks.filter(t=>!t.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));const done=state.tasks.filter(t=>t.done);main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">9月15日 火曜日 ／ デモの一日</p><h1>${open.length?'おはようございます。':'おつかれさまでした。'}</h1><p class="lead">${open.length?`まずは、<strong>今日までの仕事</strong>から確認しましょう。`:'登録されている仕事は、すべて完了しました。'}</p></div><div class="date-block">一つずつ、確認して進めましょう。</div></div><div class="today-layout"><section><div class="panel"><div class="panel-title"><h2>これからやること</h2><small>残り ${open.length}件</small></div>${open.length?taskRows(open):'<div class="empty"><div class="empty-mark">✓</div><h2>すべて完了しました</h2><p>下の「完了した仕事」から、いつでも戻せます。</p></div>'}</div>${done.length?`<details class="completed-section"><summary>完了した仕事を見る（${done.length}件）</summary><div class="panel">${taskRows(done)}</div></details>`:''}</section><aside class="aside"><section class="panel side-card inbox-card"><p class="side-label">届いた依頼</p><p class="big-number">${remaining().length}<small>件</small></p><h2>${remaining().length?'内容の確認を<br>お願いします。':'確認が終わりました。'}</h2><p>${remaining().length?'公式LINE・メール・音声メモを、読みやすく整理しています。':'登録した仕事は、左の一覧で確認できます。'}</p><button data-action="inbox" class="secondary">${remaining().length?'依頼を確認する　›':'登録した依頼を見る'}</button></section><div class="calm-note"><strong>分からないことがあったら</strong>上の「調べる」から、事務所の手順を確認できます。</div></aside></div>`;}
function taskDetail(id){const t=state.tasks.find(t=>t.id===id);if(!t){go('today');return;}nav('today');main.innerHTML=`<button class="back-button" data-action="today">‹ 今日やることに戻る</button><div class="page-heading"><div><div class="task-meta"><span class="pill ${t.due===TODAY?'urgent':''}">${esc(dateLabel(t.due))}</span><span>${esc(t.client)}</span></div><h1>${esc(t.title)}</h1></div></div><div class="detail-grid"><section class="panel paper"><h2>今回の仕事</h2><p>${esc(t.description)}</p><dl class="record"><div><dt>顧問先</dt><dd>${esc(t.client)}</dd></div><div><dt>担当</dt><dd>${esc(t.owner)}</dd></div><div><dt>期限</dt><dd>${t.due?esc(t.due.replaceAll('-',' / ')):'確認待ち'}</dd></div></dl><p class="paper-caption">期限・内容は架空の例です。法定期限の案内ではありません。</p>${t.origin==='r3'?`<button class="secondary" data-action="line-reply" data-id="r3">LINEの返信案を見る</button>`:''}</section><section class="panel paper"><h2>終わった項目にチェック</h2><p class="lead">確認できたら、下のボタンで完了にします。</p><form id="task-form" data-id="${esc(t.id)}"><ul class="check-list">${t.checks.map((c,i)=>`<li><label><input type="checkbox" required name="check${i}"><span>${esc(c)}</span></label></li>`).join('')}</ul><div class="actions"><button type="submit" class="primary">この仕事を完了にする</button></div><p class="paper-caption">完了後も取り消せます。外部への提出・送信は行いません。</p></form></section></div>`;focusMain();}
function inbox(){nav('inbox');const list=remaining();main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">受け取った依頼の確認</p><h1>届いた依頼</h1><p class="lead">内容を確認して、仕事の一覧に登録します。</p></div></div>${list.length?`<div class="inbox-list">${list.map(r=>`<article class="panel request-row"><div><div class="task-meta"><span class="pill ${r.client?'':'urgent'}">${r.client?'内容を確認':'顧問先の確認が必要'}</span><span>${r.channel} · ${r.time}</span></div><h2>${esc(r.title)}</h2><p>${r.client?esc(r.client):'顧問先が分かるまで、登録は保留しています。'}</p></div><button class="${r.client?'primary':'secondary'}" data-action="request" data-id="${r.id}">確認を始める　›</button></article>`).join('')}</div>`:'<section class="panel empty"><div class="empty-mark">✓</div><h2>届いた依頼は、すべて確認しました</h2><p>登録した内容は「今日やること」に追加されています。</p><button class="primary" data-action="today">今日やることを見る</button></section>'}${state.registered.length?`<section class="completed-section"><h2>登録した依頼（${state.registered.length}件）</h2><div class="panel" style="margin-top:16px">${state.registered.map(id=>{const r=requests.find(x=>x.id===id);return `<div class="task-row"><div><span class="pill green">✓ 登録済み</span><h3 style="margin-top:10px">${esc(r.title)}</h3></div><div class="row-actions">${r.channel==='公式LINE'?`<button class="secondary" data-action="line-reply" data-id="${id}">LINEの返信案</button>`:''}<button data-action="undo-register" data-id="${id}">登録を取り消す</button></div></div>`;}).join('')}</div></section>`:''}`;}
function startRequest(id){activeRequest=requests.find(r=>r.id===id);if(!activeRequest||state.registered.includes(id)){go('inbox');return;}draft={client:activeRequest.client,title:activeRequest.task,due:activeRequest.due,owner:'担当A'};requestStep();}
function requestStep(){nav('inbox');const r=activeRequest;main.innerHTML=`<button class="back-button" data-action="inbox">‹ 届いた依頼に戻る</button><div class="page-heading"><div><h1>内容を確認しましょう。</h1><p class="lead">元の依頼と、登録する内容を見比べてください。</p></div></div><ol class="steps" aria-label="登録の手順"><li class="active" aria-current="step"><span>1</span>内容を確認</li><li><span>2</span>登録前の確認</li></ol><div class="detail-grid"><section class="panel paper"><h2>届いた内容</h2><div class="task-meta"><span class="pill">${r.channel}</span><span>9月15日 ${r.time}</span></div>${r.channel==='公式LINE'?`<div class="line-preview"><p class="line-preview-label">公式LINEの受信イメージ（架空）</p><p class="line-sender">${esc(r.client)}</p><div class="line-bubble">${esc(r.source)}</div><p class="line-time">${r.time} ／ 受信サンプル</p></div>`:`<p class="source-text">${esc(r.source)}</p>`}<p class="paper-caption">架空の原文です。実際のLINE・メール・音声は取り込みません。</p></section><section class="panel paper"><h2>登録する内容</h2><div class="hint-box ${r.client?'':'warning'}">${esc(r.note)}</div><form id="request-form"><label class="field">顧問先<span class="required">必須</span><select name="client" required><option value="">確認した顧問先を選んでください</option>${clients.map(c=>`<option ${draft.client===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label class="field">やること<span class="required">必須</span><input name="title" value="${esc(draft.title)}" maxlength="70" required></label><label class="field">担当<select name="owner">${['担当A','担当B'].map(o=>`<option ${draft.owner===o?'selected':''}>${o}</option>`).join('')}</select></label><label class="field">確認した期限<input type="date" name="due" value="${esc(draft.due)}"><small>未確認の場合は空欄のままで構いません。</small></label><div class="actions"><button class="primary" type="submit">登録前の確認へ　›</button></div></form></section></div>`;focusMain();}
function confirmRequest(){main.innerHTML=`<button class="back-button" data-action="edit-request">‹ 内容の確認に戻る</button><div class="page-heading"><div><h1>この内容で登録しますか？</h1><p class="lead">登録すると「今日やること」に追加されます。</p></div></div><ol class="steps" aria-label="登録の手順"><li><span>1</span>内容を確認</li><li class="active" aria-current="step"><span>2</span>登録前の確認</li></ol><section class="panel paper search-wrap"><dl class="record"><div><dt>顧問先</dt><dd>${esc(draft.client)}</dd></div><div><dt>やること</dt><dd>${esc(draft.title)}</dd></div><div><dt>担当</dt><dd>${esc(draft.owner)}</dd></div><div><dt>期限</dt><dd>${draft.due?esc(draft.due.replaceAll('-',' / ')):'確認待ち'}</dd></div></dl><div class="actions"><button class="secondary" data-action="edit-request">内容を直す</button><button class="primary" data-action="register">この内容で登録する</button></div><p class="paper-caption">このブラウザ内のデモに保存します。相手への送信はありません。</p></section>`;focusMain();}
function register(){if(!activeRequest||!draft||state.registered.includes(activeRequest.id))return;const id=activeRequest.id;state.tasks.push({id:'from-'+id,...draft,done:false,description:activeRequest.note,checks:['依頼の内容を確認し、必要な対応を行った'],origin:id});state.registered.push(id);save();nav('inbox');main.innerHTML=`<section class="panel success-panel"><p class="success-label">✓ 登録しました</p><h1>仕事の一覧に追加しました。</h1><p>${esc(draft.client)}の依頼を登録しました。</p><dl class="record"><div><dt>やること</dt><dd>${esc(draft.title)}</dd></div><div><dt>期限</dt><dd>${draft.due?esc(dateLabel(draft.due)):'確認待ち'}</dd></div></dl><div class="actions"><button class="primary" data-action="today">今日やることを見る</button><button data-action="inbox">次の依頼を確認する</button></div>${activeRequest.channel==='公式LINE'?`<section class="reply-callout"><h2>続けて、LINEの返信案を確認</h2><p>受け取りのご案内を用意しています。確認・修正して使えます。</p><button class="secondary" data-action="line-reply" data-id="${id}">LINEの返信案を見る</button></section>`:''}<button class="text-button" data-action="undo-register" data-id="${id}">この登録を取り消す</button></section>`;focusMain();}
function undoRegister(id){state.tasks=state.tasks.filter(t=>t.origin!==id);state.registered=state.registered.filter(x=>x!==id);save();go('inbox');notify('登録を取り消しました。依頼は未確認に戻りました。');}
function search(){nav('search');main.innerHTML=`<div class="page-heading"><div><p class="eyebrow">事務所の手順書を探す</p><h1>分からないことを、調べる。</h1><p class="lead">知りたいことを短い言葉で入力してください。</p></div></div><div class="search-wrap"><section class="panel search-form"><form id="search-form"><label for="query">何について調べますか？</label><div class="search-line"><input id="query" name="query" type="search" placeholder="例：入社の書類" maxlength="100" required value="${esc(resultQuery)}"><button class="primary" type="submit">調べる</button></div></form><div class="examples"><h2>こちらを押しても調べられます</h2><div class="example-buttons">${notes.map(n=>`<button data-action="example" data-id="${n.id}">${esc(n.title)}</button>`).join('')}</div></div></section><div id="search-results" aria-live="polite"></div><p class="result-note">体験版では、上の3つの架空手順書だけを検索します。AIや外部検索には接続していません。</p></div>`;if(resultQuery)showSearch(resultQuery);}
function showSearch(q, explicitId){resultQuery=q;const exact=notes.find(n=>n.id===explicitId);const query=q.replace(/[\s？?]/g,'');const knownQueries=[['入社','入社の書類','入社書類','必要な書類','入社の書類を受け取るとき'],['顧問先不明','顧問先が分からない','顧問先が分からない依頼は','顧問先がわからない','依頼の振り分け'],['完了を取り消す','完了の取消','間違えて完了','未完了に戻す','仕事を間違えて完了にしたら']];const index=knownQueries.findIndex(group=>group.includes(query));const note=exact||(index>=0?notes[index]:null);$('#query').value=q;const target=$('#search-results');target.innerHTML=note?`<section class="panel search-result"><span class="pill">事務所の手順書から</span><h2 style="margin-top:16px">${esc(note.title)}</h2><p class="paper-caption">根拠：${esc(note.source)} ／ 更新：${note.updated}</p><p class="answer">${esc(note.answer)}</p><button class="source-button" data-action="source" data-id="${note.id}"><span>根拠の手順書を読む</span><span aria-hidden="true">›</span></button></section>`:`<section class="panel search-result"><h2>該当する手順書が見つかりません。</h2><p class="answer">このデモの手順書には、回答の根拠がありません。\n一般的な情報から推測せず、担当者に確認してください。</p><p class="result-note">検索した言葉：${esc(q)}</p></section>`;}
function openDialog(title,content){$('#dialog-content').innerHTML=`<h2 id="dialog-title">${esc(title)}</h2>${content}<button class="close-dialog primary" data-action="close-dialog" autofocus>閉じる</button>`;$('#dialog').showModal();}
function openReply(id){const r=requests.find(x=>x.id===id);if(!r?.reply)return;openDialog('LINEの返信案を確認',`<p><strong>返信先：${esc(r.client)}</strong></p><label class="field" for="reply-draft">必要に応じて文章を直してください。</label><textarea id="reply-draft" data-id="${esc(id)}" maxlength="1000" rows="5">${esc(state.replies?.[id]??r.reply)}</textarea><p class="paper-caption">このデモからLINEへは送信しません。文章を確認してコピーできます。</p><button class="secondary" data-action="copy-reply">返信文をコピーする</button><p id="copy-result" role="status" aria-live="polite"></p>`);}
async function copyReply(){const el=$('#reply-draft');const output=$('#copy-result');if(!el.value.trim()){output.textContent='返信文を入力してください。';el.focus();return;}try{await Promise.race([navigator.clipboard.writeText(el.value),new Promise((_,reject)=>setTimeout(()=>reject(new Error('copy timeout')),1500))]);output.textContent='コピーしました。LINEへの送信は行っていません。';}catch{if($('#dialog').open){el.focus();el.select();output.textContent='文章を選択しました。コピー操作で取り出してください。';}}}
function notify(message, undo){lastUndo=undo||null;const box=$('#feedback');box.innerHTML=`<span>${esc(message)}</span>${undo?'<button data-action="undo">取り消す</button>':''}<button class="close-feedback" data-action="dismiss">閉じる</button>`;box.hidden=false;}
function route(){const view=location.hash.slice(1);activeRequest=null;draft=null;lastUndo=null;$('#feedback').hidden=true;if(view==='inbox')inbox();else if(view==='search')search();else today();focusMain();}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const a=btn.dataset.action,id=btn.dataset.id;
  if(['today','inbox','search'].includes(a))go(a);
  else if(a==='task')taskDetail(id);
  else if(a==='reopen'){const t=state.tasks.find(t=>t.id===id);if(t){t.done=false;save();today();focusMain();notify('未完了に戻しました。');}}
  else if(a==='request')startRequest(id);
  else if(a==='edit-request')requestStep();
  else if(a==='register')register();
  else if(a==='undo-register'){const completed=state.tasks.some(t=>t.origin===id&&t.done);if(completed)openDialog('完了した仕事の登録を取り消しますか？',`<p>この依頼は仕事を完了しています。登録を取り消すと、完了の記録も消して、依頼を未確認に戻します。</p><button class="secondary" data-action="confirm-undo-register" data-id="${esc(id)}">登録と完了の記録を取り消す</button>`);else undoRegister(id);}
  else if(a==='confirm-undo-register'){$('#dialog').close();undoRegister(id);}
  else if(a==='example'){const n=notes.find(x=>x.id===id);showSearch(n.title,id);}
  else if(a==='line-reply')openReply(id);
  else if(a==='copy-reply')copyReply();
  else if(a==='source'){const n=notes.find(x=>x.id===id);openDialog(n.source,`<p class="paper-caption">更新：${n.updated} ／ 架空の手順書</p><div class="source-content">${esc(n.text)}</div>`);}
  else if(a==='close-dialog')$('#dialog').close();
  else if(a==='dismiss')$('#feedback').hidden=true;
  else if(a==='undo'&&lastUndo){lastUndo();lastUndo=null;$('#feedback').hidden=true;}
  else if(a==='reset-confirm'){openDialog('デモを最初の状態に戻しますか？','<p>このデモで登録した依頼と完了の記録を消し、最初の架空データに戻します。</p><button class="secondary" data-action="reset">最初の状態に戻す</button>');}
  else if(a==='reset'){state=initial();save();applySize();$('#dialog').close();$('#feedback').hidden=true;resultQuery='';go('today');notify('最初の架空データに戻しました。');}
});
document.addEventListener('submit',e=>{if(e.target.id==='task-form'){e.preventDefault();const t=state.tasks.find(t=>t.id===e.target.dataset.id);if(!t)return;t.done=true;const taskId=t.id;save();today();focusMain();notify('仕事を完了にしました。',()=>{const current=state.tasks.find(x=>x.id===taskId);if(current){current.done=false;save();today();focusMain();}});}
  else if(e.target.id==='request-form'){e.preventDefault();const f=new FormData(e.target);const title=String(f.get('title')).trim();if(!title){e.target.elements.title.setCustomValidity('やることを入力してください。');e.target.elements.title.reportValidity();return;}draft={client:String(f.get('client')),title,due:String(f.get('due')),owner:String(f.get('owner'))};if(!clients.includes(draft.client))return;confirmRequest();}
  else if(e.target.id==='search-form'){e.preventDefault();const q=$('#query').value.trim();if(q)showSearch(q);}
});
document.addEventListener('input',e=>{if(e.target.name==='title')e.target.setCustomValidity('');if(e.target.id==='reply-draft'){state.replies=state.replies||{};state.replies[e.target.dataset.id]=e.target.value;save();}});
$('#font-toggle').addEventListener('click',()=>{state.large=!state.large;applySize();save();});
$('#help-button').addEventListener('click',()=>openDialog('使い方',`<ol><li><strong>今日やること</strong><br>仕事の「内容を確認」を押し、終わった項目を確認して完了にします。</li><li><strong>届いた依頼</strong><br>公式LINE・メール・音声の元の文章を見ながら内容を確認し、仕事に登録します。LINEの依頼には、確認して使える返信案もあります。</li><li><strong>調べる</strong><br>言葉を入力するか、例のボタンを押して手順書を探します。</li></ol><p>文字が小さいときは、画面上の「文字を大きく」を押してください。間違えた完了や登録は取り消せます。</p>`));
$('#about-button').addEventListener('click',()=>openDialog('このデモについて','<p>事務所名・顧問先・仕事内容・手順書はすべて架空です。例示の日付は固定されています。</p><p>公式LINE・メール・音声・AI・Notion等の実サービスには接続していません。入力内容や操作は、このブラウザ内だけに保存されます。実在する個人情報は入力しないでください。</p><p>この画面は操作体験用です。本番の認証・権限管理・バックアップは実装していません。</p><button data-action="reset-confirm">デモを最初から試す</button>'));
document.querySelectorAll('[data-nav]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();go(link.dataset.nav);}));
$('.brand').addEventListener('click',e=>{e.preventDefault();go('today');});
window.addEventListener('hashchange',route);
applySize();storageNotice();route();
