(()=>{
 const slides=[...document.querySelectorAll('.slide')],select=document.querySelector('#slide-select'),memo=JSON.parse(document.querySelector('#note-data').textContent);
 const max=slides.map(s=>s.querySelectorAll('.note').length);let index=Math.min(slides.length-1,Math.max(0,(parseInt(location.hash.slice(1))||1)-1)),step=0;
 function fit(){let h=Math.max(100,innerHeight-51);document.documentElement.style.setProperty('--scale',Math.min(innerWidth/1920,h/1080));document.querySelector('.stage').style.top=h/2+'px';}
 function apply(){let s=slides[index];s.dataset.step=step;s.querySelectorAll('.frame').forEach(f=>f.hidden=+f.dataset.frame!==step);s.querySelectorAll('.note').forEach((n,i)=>n.classList.toggle('is-in',i<step));document.querySelector('#counter').textContent=`${index+1} / ${slides.length}　·　${step} / ${max[index]}`;select.value=index;document.querySelector('#note-text').textContent=memo[index];document.querySelector('#prev').disabled=!index&&!step;document.querySelector('#next').disabled=index===slides.length-1&&step===max[index];}
 function show(i,end=false){index=Math.min(slides.length-1,Math.max(0,i));step=end?max[index]:0;slides.forEach((s,j)=>s.hidden=j!==index);apply();history.replaceState(null,'','#'+(index+1));}
 function next(){if(step<max[index]){step++;apply()}else if(index<slides.length-1)show(index+1)}
 function previous(){if(step){step--;apply()}else if(index)show(index-1,true)}
 document.addEventListener('click',e=>{if(!e.target.closest('[data-no-tap],button,select,input,textarea,a'))next()});document.querySelector('.stage').addEventListener('contextmenu',e=>{e.preventDefault();previous()});
 document.addEventListener('keydown',e=>{if(e.target.closest('select,input,textarea')||e.target.isContentEditable)return;if(e.repeat&&!['ArrowRight','ArrowLeft'].includes(e.key))return;if(e.target.matches('button')&&['Enter',' '].includes(e.key))return;if(['ArrowRight','ArrowDown',' ','Enter'].includes(e.key)){e.preventDefault();next()}else if(['ArrowLeft','ArrowUp','Backspace'].includes(e.key)){e.preventDefault();previous()}else if(e.key==='Home')show(0);else if(e.key==='End')show(slides.length-1);});
 document.querySelector('#prev').onclick=previous;document.querySelector('#next').onclick=next;select.onchange=()=>show(+select.value);
 const panel=document.querySelector('#notes'),toggle=document.querySelector('#toggle-notes');toggle.onclick=()=>{panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden))};document.querySelector('#close-notes').onclick=()=>{panel.hidden=true;toggle.setAttribute('aria-expanded','false')};document.querySelector('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}};
 addEventListener('resize',fit);addEventListener('hashchange',()=>show((parseInt(location.hash.slice(1))||1)-1));fit();show(index);window.SeedOriginal={show,next,previous,get index(){return index},get step(){return step},get maxStep(){return max[index]}};
})();
