'use strict';
const $=id=>document.getElementById(id);
const originalNews=$('news-text').textContent;
for(const dialog of document.querySelectorAll('dialog')){dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});}
$('line-open').addEventListener('click',()=>$('guide-dialog').showModal());
$('social-open').addEventListener('click',()=>$('social-dialog').showModal());
$('owner-open').addEventListener('click',()=>{$('news-edit').value=$('news-text').textContent;$('owner-dialog').showModal();});
$('guide-book').addEventListener('click',()=>$('guide-dialog').close());
$('social-space').addEventListener('click',()=>$('social-dialog').close());
const answers={arrival:'ご予約内容の確認 → 到着前の施設案内 → チェックインのご案内。この順番で情報をお届けする想定です。実際のメッセージ送信は行いません。',equipment:'キッチン・Wi-Fi・バスを備えた一棟貸しという仮設定です。アメニティやお子さま用品は、実際の施設情報に合わせて掲載します。',reserve:'日程を選び、料金・キャンセル条件を確認してから予約サービスへ進む設計です。このデモでは予約・決済・在庫連携は行いません。'};
document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{$('guide-answer').textContent=answers[b.dataset.topic];}));
$('news-save').addEventListener('click',()=>{const text=$('news-edit').value.trim();if(!text){$('owner-result').textContent='本文を入力してください。';return;}$('news-text').textContent=text;$('owner-result').textContent='この画面内のお知らせに反映しました。サーバーには保存されていません。';});
$('news-reset').addEventListener('click',()=>{$('news-text').textContent=originalNews;$('news-edit').value=originalNews;$('owner-result').textContent='元の仮記事に戻しました。';});
$('motion').addEventListener('click',()=>{const stop=document.documentElement.classList.toggle('stopped');$('motion').setAttribute('aria-pressed',String(stop));$('motion').textContent=stop?'動きを再開':'動きを停止';});
$('booking-form').addEventListener('submit',event=>{event.preventDefault();const start=new Date($('arrival').value+'T12:00:00');const nights=Number($('nights').value);const result=$('booking-result');result.replaceChildren();if(!Number.isFinite(start.getTime()))return;let full=false;for(let i=0;i<nights;i++){const date=new Date(start);date.setDate(date.getDate()+i);if(date.getDay()===6)full=true;}const end=new Date(start);end.setDate(end.getDate()+nights);if(end>new Date('2027-06-01T12:00:00')){result.textContent='デモの対象期間を超えます。泊数または日程を変更してください。';return;}if(full){result.textContent='この日程には満室の設定日が含まれます。ほかの日程をお試しください。（デモ表示）';return;}const p=document.createElement('p');p.textContent=`${start.getMonth()+1}月${start.getDate()}日 → ${end.getMonth()+1}月${end.getDate()}日 / ${nights}泊 / ${$('guests').value}`;const card=document.createElement('div');card.className='plan';const label=document.createElement('span');label.textContent='素泊まり・一棟貸し（仮プラン）';const amount=document.createElement('strong');amount.textContent=`${(36000*nights).toLocaleString()}円（税込・仮料金）`;const note=document.createElement('p');note.textContent='1棟1泊36,000円の仮設定。キャンセル規定等は本番で表示します。';const button=document.createElement('button');button.type='button';button.className='outline';button.textContent='予約へ進む流れを見る →';button.addEventListener('click',()=>{button.disabled=true;button.textContent='予約サービスへの接続はありません';const msg=document.createElement('p');msg.textContent='本番では、日程と人数を引き継いで予約サービスへ移動します。この体験では予約・請求・個人情報の送信は発生しません。';card.append(msg);});card.append(label,amount,note,button);result.append(p,card);});
